### ISSUE TITLE
subscribe button not working 

### ISSUE THREAD

**Issue by freshapplenews** [SwiftWeekly/swiftweekly.github.io#1]
i am not sure why, i am pretty new to programming, for some reason the subscribe button havenot worked for me. i am sorry if it was my fault or something . i am sharing the screenshot 
![screen shot 2016-01-14 at 11 47 48 am](https://cloud.githubusercontent.com/assets/16153803/12317186/b694050e-bab4-11e5-9780-02e637a78c93.png)

**Comment by jessesquires** [comment]
Thanks @freshapplenews !

You'll need to open this from an RSS reader app, or if you tab 'subscribe' from Safari on iOS, it should open up in the Apple News app.

**Comment by freshapplenews** [comment]
thank you jessesquires
