### ISSUE TITLE
[Issue 42] October 13

### ISSUE THREAD

**Issue by BasThomas** [SwiftWeekly/swiftweekly.github.io#102]
Hey Jesse - if you're OK with this, I'd like to write next week's issue!

**Comment by jessesquires** [comment]
🎉  Sounds good to me! 😄

**Comment by jessesquires** [comment]
Generated the initial draft 😄

**Comment by BasThomas** [comment]
Thanks!

**Comment by jessesquires** [comment]
Slightly older thread, but we should add this:

https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20160926/027337.html

**Comment by jessesquires** [comment]
https://twitter.com/ericasadun/status/784528752822849536

**Comment by jessesquires** [comment]
community articles:
http://modocache.io/swift-on-android-now

**Comment by BasThomas** [comment]
Thanks Jesse, will add these! :)

**Comment by modocache** [comment]
The first weekly I wrote included a blurb on how source-breaking changes were hard to determine sometimes, and mentioned https://github.com/apple/swift/pull/4878. It turns out this caused source-breaking changes for some developers in the wild: https://github.com/apple/swift/pull/4878#issuecomment-252695257

**Comment by BasThomas** [comment]
Should I make a separate header for "community articles"? And do you want to keep these going forward (read: should I add it to the draft generator as well)?

**Comment by jessesquires** [comment]
Yeah, in previous issues we have a **Community** section below starter tasks

**Comment by jessesquires** [comment]
we can add it to the draft 👍

**Comment by jessesquires** [comment]
ping @BasThomas 😄 

we publish tomorrow AM 😊

**Comment by BasThomas** [comment]
Yup!
