### ISSUE TITLE
[Translation] Supporting general i18n in Jekyll

### ISSUE THREAD

**Issue by havocked** [SwiftWeekly/swiftweekly.github.io#12]
Hi,

I would like to start translating your posts in french in order to keep a regular challenge each week before writing my own stuff :)

How do you plan to integrate internationalization with jekyll ?
After searching a little bit on google, it seems that there is quite a few different ways to do it !

Cheers !

**Comment by jessesquires** [comment]
Hey @havocked! Awesome :tada: 

>How do you plan to integrate internationalization with jekyll?

:smile: Great question. I have no idea! I was waiting to build this until someone expressed interest in translating. Please share any information you've found. :+1: 

I've been trying to think of the best way to do this, but haven't really investigated this fully. I just pushed support for multiple authors, so each post now has a *"written by ..."* byline. I plan to hook into this for translations to provide a *"translated by ..."* byline. Right now I imagine i18n working similarly to multiple authors.

A few notes/thoughts:

- I would like to avoid additional plugins, if possible
- We should do the simplest thing first
- Leverage the YAML front matter with a `lang:` field, and maybe others?
- I'm imagining the following URL formats: `/issue-5/` (default, en) and `/fr/issue-5/` for French (same pattern for other languages)
- We'll need to update contributing docs to explain how to contribute translations

**Comment by jessesquires** [comment]
Did a quick search and briefly looked at this, didn't read it completely yet. But seems like it has some good info.
https://developmentseed.org/blog/multilingual-jekyll-sites/

**Comment by havocked** [comment]
Alright, let me check that later, after work day !

**Comment by jessesquires** [comment]
@havocked — I just realized that my previous comments might make it seem like you would need to help build internationalization support. Do you want to help build the internationalization support? Or only provide translations? (Or both?) Let me know what sounds best to you. (Any answer is fine! :smile:)

I don't want to impose this feature on you if you only wanted to translate content. So:

- If you do want to help with internationalization :+1: Let's collaborate here.

- If you only want to do translations :+1: We can track that in #13. Feel free to start translating the existing issues at anytime. For now, we can put them in `/drafts/`until the blog is ready.

**Comment by havocked** [comment]
@jessesquires Seems to be a good challenge to find the best way to implement i18n with jekyll! I cloned your project and just started working on solutions. 
In the meantime, ```/drafts/``` is a good place I could drop the translations:

How about temporarily naming files like this ?
2016-01-21-issue-6-**en**.md
2016-01-21-issue-6-**fr**.md
2016-01-21-issue-6-**xx**.md
...

So, long story short, to answer your question:
I'm fine for both! :punch:

First, maybe it's better to concentrate on how we can provide your website a flexible way to i18n.

Cheers

**Comment by jessesquires** [comment]
Awesome! :tada: I just wanted to check.

>How about temporarily naming files like this?

Actually, for now, let's keep file names the same, and put them in `/_drafts/fr/`. So:

```
/_drafts/fr/2016-01-21-issue-6.md
```

That sound good?

**Comment by havocked** [comment]
Yup good for me !

Alright so based on your previous link:
>Did a quick search and briefly looked at this, didn't read it completely yet. But seems like it has some good info.
https://developmentseed.org/blog/multilingual-jekyll-sites/

I followed the trail and found this repo: 
https://github.com/climatescope/climatescope.github.io/tree/publish/app
It's based on a Nate Smith's [tweet](https://twitter.com/nas_smith/status/587416028365381632), the author of the linked article.

It looks like, if we gonna go without plugins, we can do it that way (seems to me that it will complexify your website's architecture)

**Comment by jessesquires** [comment]
This looks awesome. Nice work :+1: 

>Seems to me that it will complexify your website's architecture

Yes, this is expected. However, that site is substantially more complex than this one, it seems. Looking through the `_config.yml` and `_posts/` — it seems straight forward.

Some notes:

Climatescope uses this pattern for URLs:

```bash
# English
http://global-climatescope.org/en/
http://global-climatescope.org/en/blog/
http://global-climatescope.org/en/download/

# Spanish
http://global-climatescope.org/es/
http://global-climatescope.org/es/blog/
http://global-climatescope.org/es/datos/
```

Moving to `/en/` would break existing links, etc. for us. So I propose using:

```bash
# English
http://swiftweekly.github.io/
http://swiftweekly.github.io/issue-0/
http://swiftweekly.github.io/issue-2/

# French
http://swiftweekly.github.io/fr
http://swiftweekly.github.io/fr/issue-0/
http://swiftweekly.github.io/fr/issue-2/
```

I'm pretty sure we'll be able to make this work. For `/_posts/`, we should probably have sub-directories per language. `/en/`, `/fr/`, `/es/`, etc.

Still thinking about visual design.

**Comment by havocked** [comment]
`Still thinking about visual design.`
Maybe the bar in the header can be used for i18n using emoji flags.
Could be easly modular if there are many languages.

<img width="655" alt="translation" src="https://cloud.githubusercontent.com/assets/7999585/12411276/c03fdd68-be96-11e5-9541-abdf130a2976.png">

**Comment by jessesquires** [comment]
New branch for this work, [`i18n_issue_12 `](https://github.com/SwiftWeekly/swiftweekly.github.io/tree/i18n_issue_12).
