### ISSUE TITLE
[46] Issue 46, Nov 10

### ISSUE THREAD

**Issue by jessesquires** [SwiftWeekly/swiftweekly.github.io#121]
Next issue by @modocache 😄

**Comment by jessesquires** [comment]
initial draft pushed
https://github.com/SwiftWeekly/swiftweekly.github.io/commit/45dbccd51a68b846071254449704fac0c8cadf5f

**Comment by jessesquires** [comment]
😱 Note worthy:

https://twitter.com/chandlerc1024/status/794318137445359616

**Comment by modocache** [comment]
@jessesquires I added a blurb about LLVM moving to GitHub in #123. As I mention there, I wouldn't hold my breath, though. There are a lot of issues involved in moving -- the multirepo vs. monorepo decision appeared to be super contentious, and I don't see a consensus being reached anytime soon. No matter which is chosen, there are a lot of licensing and tooling issues as well.

**Comment by modocache** [comment]
As usual, help with Swift evolution and the mailing lists would be greatly appreciated! /cc @BasThomas

**Comment by jessesquires** [comment]
> the multirepo vs. monorepo decision appeared to be super contentious

Shocking 😆 😅

**Comment by BasThomas** [comment]
Will submit PRs when I find something interesting. :)

**Comment by modocache** [comment]
OK, if anyone has any material at all about the mailing lists or Swift evolution, now's the time to add it, please! I am very lost when it comes to covering that stuff. 🙇 /cc @BasThomas @jessesquires

**Comment by BasThomas** [comment]
Give me a sec!

**Comment by modocache** [comment]
I'd appreciate it if you added it now, and then you or I can revisit it tomorrow. 👍

**Comment by BasThomas** [comment]
Sorry, timezones 😕
Saw you added it just now, thanks for that!

**Comment by BasThomas** [comment]
🙌

**Comment by BasThomas** [comment]
Nvm, you haven't published yet. On purpose?

**Comment by jessesquires** [comment]
👍 💯
