### ISSUE TITLE
The Mistakes Most Swift Developers Don't Know They're Making

### ISSUE THREAD

**Issue by hollaur** [SwiftWeekly/swiftweekly.github.io#122]
[The Mistakes Most Swift Developers Don't Know They're Making](https://www.toptal.com/swift/top-swift-development-mistakes)

Swift is the new programming language created to be a modern replacement for Objective-C in iOS and OS X application development. In general, a skilled Swift developer is usually someone who is already experienced with Objective-C, and that, among other things, might lead them to write Swift code using Objective-C best practices, which can cause some bad mistakes.

In this article, Toptal Freelance Software Engineer Nilson Souto outlines the most common mistakes Swift developers should be aware of.

**Comment by jessesquires** [comment]
Thanks @hollaur ! 😄 

I'm not sure this would be suited for the Swift Weekly audience. We try to share community articles on very swift-specific topics or technical details. But this looks like a great post for the Cocoa community in general! 😊
