### ISSUE TITLE
[47] Issue #47, Nov 17th

### ISSUE THREAD

**Issue by codeOfRobin** [SwiftWeekly/swiftweekly.github.io#126]
Referencing tweet: https://twitter.com/jesse_squires/status/797518315048448000

Hey! I'd love to help out with the new issue.

**Comment by BasThomas** [comment]
Hey, thanks for the offer! Are you interested in writing the full issue, or just helping out where you can?

**Comment by codeOfRobin** [comment]
Let's start with helping out where I can 😅

**Comment by BasThomas** [comment]
That's fine! Let me know if you have any questions.

**Comment by jessesquires** [comment]
Notable info for this issue:
https://twitter.com/practicalswift/status/797895401885999104

**Comment by jessesquires** [comment]
Thanks @codeOfRobin and @BasThomas !

I'll jump-in every once in awhile and answer any questions.

@codeOfRobin -- Checkout the contributing guidelines in the repo, and previous issues for examples. 😄

**Comment by jessesquires** [comment]
✨ Friendly ping ✨ 

Just a heads up that this issue should be ready by Wednesday night / Thursday morning if we want to publish.

**No pressure at all** — I was planning on skipping this week, so this is entirely up to you! Feel free to say no! 😄

**Comment by BasThomas** [comment]
Yes, will work on finishing this today. A promise is a promise!

**Comment by codeOfRobin** [comment]
I couldn't make a PR for functionalemoji (jekyll won't build on my machine for some reason), so could you add it @BasThomas (referencing issue #127 )

**Comment by jessesquires** [comment]
@codeOfRobin -- No worries. As long as you can write markdown, you can still submit the PR 😄 

(we'll fixup anything if needed)

**Comment by codeOfRobin** [comment]
@jessesquires Done! 👍

**Comment by BasThomas** [comment]
The issue doesn't show up when previewing with Jekyll after moving it to _posts. 🤔
Any idea @jessesquires?

**Comment by jessesquires** [comment]
did you run bundle install after cloning from github?

https://github.com/SwiftWeekly/swiftweekly.github.io#installation

**Comment by BasThomas** [comment]
I did, yep!

**Comment by BasThomas** [comment]
Strange, must have missed something. "It just works" on my MacBook. ¯\_(ツ)_/¯
