### ISSUE TITLE
About functional emoji....

### ISSUE THREAD

**Issue by codeOfRobin** [SwiftWeekly/swiftweekly.github.io#127]
Referencing @ericasadun's tweet that was mentioned in the "Finally" section in [this review](http://swiftweekly.github.io/issue-45/).
There's a twitter account dedicated to explaining map, reduce and filter via emoji: https://twitter.com/functionalemoji

**Comment by jessesquires** [comment]
👍 Thanks @codeOfRobin ! 

Feel free to add this for issue 47
