### ISSUE TITLE
[48] Issue #48, Dec 1st

### ISSUE THREAD

**Issue by BasThomas** [SwiftWeekly/swiftweekly.github.io#142]
@jessesquires, are you writing issue 48? Or do you want someone else to pick it up?

**Comment by BasThomas** [comment]
Either way, as a reference:

[SE-0143 accepted](https://lists.swift.org/pipermail/swift-evolution-announce/2016-November/000295.html)
[SE-0146 under review](https://lists.swift.org/pipermail/swift-evolution-announce/2016-November/000296.html)

**Comment by jessesquires** [comment]
I was planning on skipping next week because it's a US holiday. (Thanksgiving) I'm sure a lot of Apple folks will be out and repos will quiet down.

How about we publish Issue 48 on Dec 1? (So Issue 48 will cover 2 weeks.)

**Comment by jessesquires** [comment]
Would also be good to mention this:
https://github.com/swift-server/work-group

**Comment by BasThomas** [comment]
That seems like a good idea. Have we not discussed the work group yet, by the way? 😱

**Comment by BasThomas** [comment]
Ah, it was discussed in issue 44 (https://swiftweekly.github.io/issue-44/)

**Comment by jessesquires** [comment]
"Rule of thumb" from Jordan Rose:
https://lists.swift.org/pipermail/swift-users/Week-of-Mon-20161114/003982.html

**Comment by BasThomas** [comment]
https://twitter.com/slava_pestov/status/802942139873173504 + https://github.com/apple/swift/pull/5935

> The culmination of two years chipping away at technical debt in Swift generics -- still needs cleanup and splitting

**Comment by BasThomas** [comment]
https://github.com/apple/swift/pull/5904

**Comment by jpsim** [comment]
Automatically building SourceKit on Linux: https://lists.swift.org/pipermail/swift-dev/Week-of-Mon-20161121/003554.html

**Comment by BasThomas** [comment]
SE-0146 accepted: https://lists.swift.org/pipermail/swift-evolution-announce/2016-November/000298.html

**Comment by BasThomas** [comment]
Greg Heo's [CollectionOfOne](https://swiftunboxed.com/open-source/CollectionOfOne/) and [IteratorOverOne](https://swiftunboxed.com/open-source/IteratorOverOne/) articles (Community)

**Comment by jessesquires** [comment]
👍

**Comment by BasThomas** [comment]
Woah, totally missed it is Thursday already. Great work, @jessesquires!
