### ISSUE TITLE
New swift library for new issue

### ISSUE THREAD

**Issue by vladdmitriev** [SwiftWeekly/swiftweekly.github.io#143]
Hello,

My name is Vlad. Our company Cleveroad have created our new swift library - CRNetworkButton. This is a send button for iOS - https://github.com/Cleveroad/CRNetworkButton

"Anytime the users click on the button, they will see the animation that informs them of the progress and completion."

![demo_ 2](https://cloud.githubusercontent.com/assets/20402305/20597533/f7f79250-b24c-11e6-86b6-9dbef1d80f60.gif)

Could you add it to your - Swift Weekly?

**Comment by BasThomas** [comment]
Hi Vlad! I don't think this is really suited for Swift Weekly. We cover Swift OSS in this brief, but no projects or libraries. Thank you for your understanding! 🙂
