### ISSUE TITLE
[Translation] Brazilian Portuguese

### ISSUE THREAD

**Issue by rafaelcsa** [SwiftWeekly/swiftweekly.github.io#18]
Hi @jessesquires,

Seeing how well the french translation seems to be turning, I'd like to offer my translations to Brazilian Portuguese if you don't mind. This should hopefully help some people in my country and also help me keep in touch with what goes on in the Swift world more closely. 

Let me know if this is fine by you!

Cheers!

**Comment by jessesquires** [comment]
Thanks @rafaelcsa ! :smile: This is awesome :bow: 

I'm still working on getting the translation architecture setup in jekyll. For now, feel free to open a PR and put translated issues in `/_drafts/pt-BR/` and submit to the [`portuguese_brazil`]( https://github.com/SwiftWeekly/swiftweekly.github.io/tree/portuguese_brazil) branch.

I'm hoping to have enough time this weekend to finish the infra work in jekyll to make this easy. I'll keep you updated!

**Comment by rafaelcsa** [comment]
Awesome! I'm working on the first issue. Hopefully I'll get a couple done this weekend.

Cheers!

**Comment by jessesquires** [comment]
Hey @rafaelcsa ! :smile: 

Any updates here? Feel free to open a pull request and just add commits to it as you go.

**Comment by rafaelcsa** [comment]
Hey @jessesquires,

Just created a pull request with the translation of the first issue. Sorry for taking so long. Hopefully I'll get the next few done much quicker now.

Cheers

**Comment by jessesquires** [comment]
:tada: :smile:
