### ISSUE TITLE
Sort authors by amount of posts

### ISSUE THREAD

**Issue by BasThomas** [SwiftWeekly/swiftweekly.github.io#223]
The authors page (http://swiftweekly.github.io/authors/) is now "sorted" by the list [here](https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/_data/authors.yml). It might be nice if we can sort them by amount of posts.

**Comment by RomanVolkov** [comment]
Be honest @BasThomas, you just want to be closer to top😀

**Comment by BasThomas** [comment]
Obviously. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jessesquires** [comment]
docs on sorting here: https://jekyllrb.com/docs/templates/ (search for "sort")

**Comment by jessesquires** [comment]
https://shopify.github.io/liquid/filters/sort/
