### ISSUE TITLE
Add more info to tweets?

### ISSUE THREAD

**Issue by BasThomas** [SwiftWeekly/swiftweekly.github.io#258]
I think we can do better with the tweets. They are generic, and don't really give any idea as to what has been written about that week... but we do have a bunch of characters left to do so.

**Comment by jessesquires** [comment]
Ha 😄 

Agreed, but how since they are automated?

**Comment by jessesquires** [comment]
The twitter preview does provide a few sentences:

<img width="586" alt="screen shot 2017-05-16 at 9 09 04 am" src="https://cloud.githubusercontent.com/assets/2301114/26116266/63c84f72-3a17-11e7-8a21-020454c612e4.png">

**Comment by BasThomas** [comment]
Ha, that's actually pretty good. Oh Tweetbot. 

This might not be that big of an issue then. 

@automation: I think we could access some yaml tag and use that.

**Comment by gregheo** [comment]
Newsletter logo & title at minimum, so it says "Swift Weekly Brief Issue 66" in the card. Easy to do with some extra meta tags (https://dev.twitter.com/cards/overview)

**Comment by jessesquires** [comment]
With #278 merged, I think we're good here? Probably not much else that's actionable at the moment... ?

**Comment by BasThomas** [comment]
Yep, think so!
