### ISSUE TITLE
[Help wanted] Writers for upcoming issues in June and July

### ISSUE THREAD

**Issue by jessesquires** [SwiftWeekly/swiftweekly.github.io#266]
### Taking time off

Hey everyone 😄 

I will be "off the grid" coming up and I'm looking for volunteers for the next few issues. If no one is available, that's fine, we'll just take a break for those weeks.

### Upcoming issues:

- [x] 74: June 15, @benasher44 
- [x] 75: June 22 @gregheo 
- [x] 76: June 29 @garricn 
- [x] 77: July 6 @RomanVolkov

### Responsibilities:

I'll be getting online periodically to help with anything that comes up. As usual, we'll also keep a GitHub issue open for each Swift Weekly issue to gather notes to help the current writer.

For anyone in the OSS community new to contributing, see our [contributing guide](https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/CONTRIBUTING.md). By now, **everything is automated** (emails, tweets, RSS). All you need to do is write some markdown, and then push to GitHub! 😄

**Comment by jessesquires** [comment]
cc @gregheo @BasThomas @modocache — let me know if you guys are interested! If not, that's ok too. 😄

**Comment by jessesquires** [comment]
If interested, please comment here and I'll update the main issue! 👍

**Comment by benasher44** [comment]
I'd be happy to do #74!

**Comment by jessesquires** [comment]
@benasher44 Just added you to the `authors.yml` and GH org. https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/_data/authors.yml#L21-L24

**Comment by BasThomas** [comment]
And here I was thinking you just got "on the grid". 🤔
I am afraid I wont be able to write any full issues - graduation and all that. Like Jesse though, I will of course be hanging around, so let me know if there's any questions and I am happy to help out. 😃

**Comment by jessesquires** [comment]
@BasThomas - Ha, yeah 😅 After this, I'll be back and won't be leaving for awhile.

**Comment by gregheo** [comment]
I'll take 75. If there's a lack of volunteers, I can publish 75 on the 29th so there's an issue every two weeks.

**Comment by jessesquires** [comment]
Thanks @gregheo ! 👍  Sounds good to me. 

If we don't have anymore volunteers, I'll update the schedule in the main issue.

**Comment by garricn** [comment]
I can do 76

**Comment by RomanVolkov** [comment]
I would like to get 77.

**Comment by jessesquires** [comment]
Thanks @garricn and @RomanVolkov ! If you have any questions, let me know.

@BasThomas Should also be able to help answer questions. 😄

**Comment by garricn** [comment]
Looking forward to it 🤗 Thank you for the opportunity!

**Comment by BasThomas** [comment]
Awesome, thanks all! Looking forward to these 😃

**Comment by RomanVolkov** [comment]
Cool👍🏻

**Comment by BasThomas** [comment]
Friendly ping, @benasher44 :)

**Comment by benasher44** [comment]
Hi! Did I forget something? I've been working on 74 locally and will push my WIP branch this morning!

**Comment by BasThomas** [comment]
Nice!

**Comment by benasher44** [comment]
What I have for 74 so far is up! #268

**Comment by garricn** [comment]
To be sure, when should the "next" issue be created and what time period should it cover? For example, issue 74 will be released this Thursday, correct? So should Issue 75 be created on Thursday after Issue 74 is released and should it cover the time period of this Thursday through the following Wednesday?

**Comment by gregheo** [comment]
@garricn that sounds about right. You could create the draft earlier in `_drafts` with no ill effects, but makes sense to run the script on Thursday so there's only one issue "in flight" at a time.

**Comment by jessesquires** [comment]
yep! that's right @garricn ! 👍 

thanks @gregheo ! ❤️
