### ISSUE TITLE
Starter tasks for issue 15

### ISSUE THREAD

**Issue by modocache** [SwiftWeekly/swiftweekly.github.io#28]
Some new starter tasks:

- [SR-1046](https://bugs.swift.org/browse/SR-1046): Make sure we use the same test runner executable for both the Swift and swift-corelibs-xctest builds.
- [SR-1047](https://bugs.swift.org/browse/SR-1047): Test the Python used in the swift-corelibs-xctest project as part of the XCTest test suite.
- [SR-1048](https://bugs.swift.org/browse/SR-1048): Build debug/release versions of swift-corelibs-xctest when building debug/release versions of Swift.

This task from last week is still up for grabs:

- [SR-875](https://bugs.swift.org/browse/SR-875): Improve regex support in the swift-corelibs-xctest test suite. This'll make it easier to write tests for that project.

**Comment by jessesquires** [comment]
:tada: :bow:
