### ISSUE TITLE
[76] Issue #76 - June 29, 2017

### ISSUE THREAD

**Issue by garricn** [SwiftWeekly/swiftweekly.github.io#280]

**Comment by jessesquires** [comment]
thanks @garricn ! 🎉

**Comment by jpsim** [comment]
https://twitter.com/catfish_man/status/877991651548975104

**Comment by gregheo** [comment]
SE-0180 back in review
https://github.com/apple/swift-evolution/blob/master/proposals/0180-string-index-overhaul.md

**Comment by jessesquires** [comment]
Swift for VS code -- important for non-Apple Platform Swift development
https://owensd.io/2017/06/02/apous-early-preview/

**Comment by garricn** [comment]
Evo app's Swift backend is not open source: https://github.com/unnamedd/swift-evolution-backend

**Comment by BasThomas** [comment]
How Swift's `sort()` is optimized: https://twitter.com/stevenhepting/status/878339681485635585

**Comment by garricn** [comment]
I consume therefore I am: https://twitter.com/harlanhaskins/status/878499165663240192

**Comment by garricn** [comment]
@gregheo Regarding SE-0180, the proposal is in Active Review but there is already a PR opened that implements it. Is that normal?

**Comment by garricn** [comment]
Asking for feedback on Swift Evolution: https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20170619/037672.html

**Comment by BasThomas** [comment]
@garricn: on an active proposal with its implementation already done: that happens from time to time, yep!

**Comment by gregheo** [comment]
@garricn normal, as Bas mentioned. It's not merged in, so it's a good chance to get an early look and then spot some issues as happened here

**Comment by garricn** [comment]
I enjoy these Swift puzzles. I hope to see more: https://twitter.com/codafi_/status/878330155642396673

**Comment by gregheo** [comment]
Brisk, a macOS app for submitting radars (mentioned before in this publication) hits v1.0 and a quick 1.0.1 follow-up release
https://github.com/br1sk/brisk

**Comment by garricn** [comment]
This seems interesting: can anyone give me some thoughts on this... It looks like it addresses multiple radars. https://github.com/apple/swift/pull/10565

**Comment by garricn** [comment]
https://twitter.com/s1ddok/status/879406585939984386

**Comment by BasThomas** [comment]
https://twitter.com/LouisDhauwe/status/879441402870079488

**Comment by garricn** [comment]
https://github.com/apple/swift/pull/10241#issuecomment-311384734

**Comment by jessesquires** [comment]
Key paths update
https://github.com/apple/swift/pull/10583

Source compatibility fixes
https://github.com/apple/swift/pull/9466

**Comment by jessesquires** [comment]
Swift unwrapped 😊 

https://spec.fm/podcasts/swift-unwrapped/70319

**Comment by jessesquires** [comment]
@gregheo's disappointing post that the new encoders are just wrappers around NSJSONSerialization. 

`¯\_(ツ)_/¯`

https://swiftunboxed.com/stdlib/json-encoder-encodable/

**Comment by gregheo** [comment]
@jessesquires the *post* was disappointing, or the *conclusion* was disappointing?! 😈

**Comment by modocache** [comment]
Apple developed index-while-building on their internal Clang fork in time for Xcode 9. The changes are being merged to swift-clang, the Swift project's fork of Clang, in apple/swift-clang pull request 95 (87 files changed, 9,127 lines added, 30 lines deleted!). As far a I can tell, there isn't a diff up for this on the upstream Clang repository, but I'm not sure.

**Comment by garricn** [comment]
@jessesquires @gregheo @BasThomas Anyone find anything interesting re:

1. Proposals (Proposed/Accepted/Rejected/)
2. Mailing Lists
3. Starter Tasks

Thank you.

**Comment by BasThomas** [comment]
1. SE-180 is back in review: https://github.com/apple/swift-evolution/commit/8de3eb3e9e075999035ec5083bf5ffef73086dcf (might still get accepted / rejected tomorrow?)

**Comment by garricn** [comment]
Anything else on the mailing lists?

**Comment by gregheo** [comment]
re Ben's PR mentioned by Bas above — details on...the mailing list.
https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20170626/037776.html

**Comment by garricn** [comment]
@jessesquires @BasThomas It appears that there are no new starter tasks. Am I correct? Shall I just include some old ones?

**Comment by jessesquires** [comment]
@garricn feel free to just omit the starter task section (or any other section if there's nothing to add) 😄

**Comment by jessesquires** [comment]
Thanks folks for all the fantastic work! 💯 

I merged #281, fixed some typos, and added some pull quotes for the mailing list items. Looks like everything is good to go! 

@garricn The last thing to do is move the issue from `_drafts/` to `_posts/` in the morning. 👏

**Comment by jessesquires** [comment]
@gregheo the conclusion 😅😂

**Comment by garricn** [comment]
Will do.

**Comment by garricn** [comment]
I didn't want to push to master so I opened #283 @BasThomas @gregheo

**Comment by gregheo** [comment]
Congrats @garricn! 🎉

**Comment by garricn** [comment]
Thank you for the opportunity and for helping so much with the issue. It was fun and I look forward to doing it again! 😁

**Comment by jessesquires** [comment]
Thanks so much @garricn!
