### ISSUE TITLE
De-dupe Twitter card tags

### ISSUE THREAD

**Issue by gregheo** [SwiftWeekly/swiftweekly.github.io#282]
Turns out the Jekyll SEO thing already adds some Twitter card tags and the recent commit (97bc9235) duplicates some, and adds some missing ones.

We should consolidate and either push the missing metadata to the SEO code so it generates all the tags, or disable Twitter card support in the SEO code and use the manually-generated tags.

**Comment by jessesquires** [comment]
Ahh yep, `jekyll-seo-tag` attempts to do some of this -- forgot about that. I remember when I set that up, I had trouble getting it generate all of the correct Twitter card tags. 

Might be better to just leave the manual tags there.

I'll need to see if `jekyll-seo-tag` gives us any other benefits.
