### ISSUE TITLE
[77] Issue #77 - June 6, 2017

### ISSUE THREAD

**Issue by RomanVolkov** [SwiftWeekly/swiftweekly.github.io#285]

**Comment by jessesquires** [comment]
Thanks @RomanVolkov! 🙌🎉

**Comment by BasThomas** [comment]
https://oleb.net/blog/2017/06/chris-lattner-wwdc-swift-panel/

**Comment by jpsim** [comment]
HN conversation for Ole's post: https://news.ycombinator.com/item?id=14673059

**Comment by jessesquires** [comment]
@RomanVolkov I just pushed an initial draft template in `_drafts/` 😄

**Comment by BasThomas** [comment]
I think Roman already made [a branch](https://github.com/SwiftWeekly/swiftweekly.github.io/tree/draft/issue-77?files=1) for that? 😬

**Comment by jessesquires** [comment]
Oops! I'll merge into there.

**Comment by jessesquires** [comment]
Pretty good overview of the new encoders/decoders:
http://benscheirman.com/2017/06/ultimate-guide-to-json-parsing-with-swift-4/

**Comment by RomanVolkov** [comment]
Yeah, I made a branch for that:D

**Comment by jessesquires** [comment]
@RomanVolkov -- anything that you think is interesting! if you are unsure, post a link here and @SwiftWeekly/writers can help decide if it's worth including or not 😄 

I think Erica's "unwrap or die" should be included 👍

**Comment by jessesquires** [comment]
Community:
Simon's book is now free 💯 
https://twitter.com/flexmonkey/status/881789384735039489

**Comment by BasThomas** [comment]
@jessesquires / @RomanVolkov - do know that Erica's pitch was already included in last week's Brief: https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/_posts/2017-06-29-issue-76.md#mailing-lists. So make sure to not repeat just that. ;)

**Comment by BasThomas** [comment]
https://github.com/apple/swift-evolution/pull/729

**Comment by modocache** [comment]
Perhaps relevant to people interested in Swift: as [mentioned in LLVM Weekly](http://llvmweekly.org/issue/183), LLVM's bug tracker now has a "beginner" keyword, akin to Swift JIRA's "StarterBug" label. There's only one "beginner" bug right now, but if you know people on the Swift team who work on [swift-clang](http://github.com/apple/swift-clang) or [swift-llvm](http://github.com/apple/swift-llvm), you should pester them to label more bugs as "beginner". You can view all of the beginner LLVM bugs [here](https://bugs.llvm.org/buglist.cgi?keywords=beginner&list_id=119844&resolution=---).

**Comment by RomanVolkov** [comment]
wdyt about 
https://github.com/fastred/DeallocationChecker 
https://github.com/unnamedd/swift-evolution-backend sources codes as example of production swift backend code
and this https://github.com/hetelek/Neural-Network-Playground for iPads?

**Comment by RomanVolkov** [comment]
closed by mistake!

**Comment by BasThomas** [comment]
The Weekly is more about the Swift.org project, not really open source Swift projects. :)

**Comment by RomanVolkov** [comment]
@BasThomas good point💯

**Comment by jessesquires** [comment]
@RomanVolkov -- looking great! 💯 I push some minor edits and opened #287. 😄

**Comment by RomanVolkov** [comment]
@jessesquires it is obvious that you are doing this not for the first time:) Your formulations are really better than mine😀👍🏻

**Comment by jessesquires** [comment]
@RomanVolkov haha 😄 you're doing great! 💯
