### ISSUE TITLE
[17] Add StarterBug for stdlib tests

### ISSUE THREAD

**Issue by modocache** [SwiftWeekly/swiftweekly.github.io#30]
- [SR-1124](https://bugs.swift.org/browse/SR-1124): Migrate legacy Swift stdlib tests to the StdlibUnittest framework. This would make those tests easier to read and maintain. Over the course of completing this task, newcomers to Swift development would become familiar with several tools used to test the compiler. There are 35 tests in total--feel free to claim individual tests by commenting on the task.

**Comment by jessesquires** [comment]
Thanks @modocache ! :smile:
