### ISSUE TITLE
"First external contribution to the Swift refactoring family"

### ISSUE THREAD

**Issue by kud1ing** [SwiftWeekly/swiftweekly.github.io#313]
* https://twitter.com/xge_apple/status/909920319766278145
* https://github.com/apple/swift/pull/11851

**Comment by BasThomas** [comment]
Hey, thanks @kud1ing! I've added the links to this week's issue notes: https://github.com/SwiftWeekly/swiftweekly.github.io/issues/312

**Comment by kud1ing** [comment]
Thanks.
