### ISSUE TITLE
Use `jekyll-mentions` for linking GitHub profiles for commits & PRs section

### ISSUE THREAD

**Issue by jessesquires** [SwiftWeekly/swiftweekly.github.io#316]
https://github.com/jekyll/jekyll-mentions

currently we (sometimes) do this manually. this should allow us to just type `@username` and have it automatically "linkified".

we'll probably need to audit old issues to use this once implemented.

**Comment by BasThomas** [comment]
Nice! I can do the audit. :)

**Comment by jessesquires** [comment]
🎉 Thanks @BasThomas ! 

Just need to add it here to enable it
https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/_config.yml#L6

**Comment by jessesquires** [comment]
Also, turns out we can remove this from the gemfile:
https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/Gemfile#L4

(it's included in `github-pages`)

**Comment by jeroenleenarts** [comment]
AM I correct in concluding that the suggested feature in this ticket has been implemented back in 2018?

**Comment by jessesquires** [comment]
No, nothing implemented. 

The discussion above was just about including the dependency.
