### ISSUE TITLE
[90] Issue #90 - Oct 5, 2017

### ISSUE THREAD

**Issue by jessesquires** [SwiftWeekly/swiftweekly.github.io#318]
To contribute to this issue, simply leave a comment here. Please also review [our contributing guidelines](https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/CONTRIBUTING.md).

The current draft for this issue in [`_drafts/`](https://github.com/SwiftWeekly/swiftweekly.github.io/tree/master/_drafts). If you want to contribute directly, [open a pull request](https://github.com/SwiftWeekly/swiftweekly.github.io/compare?expand=1).

**Comment by jessesquires** [comment]
https://github.com/apple/swift/pull/11869

**Comment by BasThomas** [comment]
https://twitter.com/slava_pestov/status/913656701840060416

**Comment by jessesquires** [comment]
hey @BasThomas would you be interested in taking this issue? 😊

**Comment by BasThomas** [comment]
Yes!

**Comment by BasThomas** [comment]
https://github.com/apple/swift-evolution/issues/751

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
https://twitter.com/slava_pestov/status/913897860420182016

**Comment by BasThomas** [comment]
Finally? https://twitter.com/Catfish_Man/status/913922418833420289

**Comment by BasThomas** [comment]
XNU Kernel (mirror) on GH: https://github.com/apple/darwin-xnu

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RomanVolkov** [comment]
https://twitter.com/clattner_llvm/status/914366072144371712

**Comment by BasThomas** [comment]
Mailing list: https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20170925/040009.html

**Comment by jpsim** [comment]
> @dgregor79's recent generic signature builder improvements sped up the type checking phase of building the standard library by 3x

https://twitter.com/slava_pestov/status/914594813697130496

**Comment by gregheo** [comment]
Recursive protocol constraints for standard library

https://github.com/apple/swift/pull/11923

**Comment by BasThomas** [comment]
https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20171002/040053.html

**Comment by RomanVolkov** [comment]
https://twitter.com/slava_pestov/status/914729705827209216

**Comment by BasThomas** [comment]
https://twitter.com/Chris__Bailey/status/914925288240316416

**Comment by BasThomas** [comment]
https://twitter.com/slava_pestov/status/915110709209456640

**Comment by BasThomas** [comment]
https://twitter.com/tkremenek/status/915229686740926465

**Comment by jessesquires** [comment]
https://github.com/apple/swift/pull/12200

**Comment by modocache** [comment]
A good starter bug in apple/swift/lib/Driver: https://bugs.swift.org/browse/SR-3352

**Comment by modocache** [comment]
Here's a better starter bug, also in the Driver: https://bugs.swift.org/browse/SR-6055

**Comment by jessesquires** [comment]
which is the fastest?
https://github.com/swift-server/which_is_the_fastest

**Comment by BasThomas** [comment]
https://swift.org/blog/dictionary-and-set-improvements/

**Comment by RomanVolkov** [comment]
Wow https://twitter.com/fchollet/status/915653994176954368
