### ISSUE TITLE
Add paging to homepage

### ISSUE THREAD

**Issue by BasThomas** [SwiftWeekly/swiftweekly.github.io#319]
The list is getting a tad long, had to scroll so much to get to the bottom

**Comment by jessesquires** [comment]
ha 😄

**Comment by jessesquires** [comment]
Actually, I kind of like *not* having this paged. I like how simple it is, and it's probably not a priority for people to read *really old* issues.

Especially now with the new search bar up top (#353), seems less valuable.

Also, this is how [llvm weekly](http://llvmweekly.org) does it.

-----

@BasThomas -- thoughts? still think we should do this?

**Comment by BasThomas** [comment]
Think it's not that big of an issue indeed; let's close for now. :)

**Comment by fassko** [comment]
I think now this issue is actual again.

**Comment by BasThomas** [comment]
It's still in the same state; or what are you referring to with it being an issue?

**Comment by fassko** [comment]
I think list is quite long and paging makes sense.

**Comment by jeroenleenarts** [comment]
@fassko Pagination is already available. If we want to decrease the number of items per page...

https://github.com/SwiftWeekly/swiftweekly.github.io/blob/main/_config.yml#L40
