### ISSUE TITLE
[91] Issue #91 - Oct 12, 2017

### ISSUE THREAD

**Issue by BasThomas** [SwiftWeekly/swiftweekly.github.io#322]
To contribute to this issue, simply leave a comment here. Please also review [our contributing guidelines](https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/CONTRIBUTING.md).

The current draft for this issue in [`_drafts/`](https://github.com/SwiftWeekly/swiftweekly.github.io/tree/master/_drafts). If you want to contribute directly, feel free to [open a pull request](https://github.com/SwiftWeekly/swiftweekly.github.io/compare?expand=1).

**Comment by jessesquires** [comment]
https://twitter.com/ashfurrow/status/915930734082306050

**Comment by BasThomas** [comment]
https://twitter.com/harlanhaskins/status/916023399717179394

**Comment by BasThomas** [comment]
https://github.com/apple/swift/pull/12295

**Comment by BasThomas** [comment]
https://swift.org/blog/xcode-9-1-improves-display-of-fatal-errors/

**Comment by gregheo** [comment]
Another 16% stdlib typecheck speedup: https://github.com/apple/swift/pull/12321

(Source: https://twitter.com/slava_pestov/status/916452691840241664)

**Comment by BasThomas** [comment]
184 accepted with revisions: https://lists.swift.org/pipermail/swift-evolution-announce/2017-October/000405.html

**Comment by BasThomas** [comment]
https://twitter.com/slava_pestov/status/917189019888259073

**Comment by BasThomas** [comment]
https://twitter.com/slava_pestov/status/917280154245775360

**Comment by BasThomas** [comment]
https://twitter.com/olebegemann/status/917388018989912064

**Comment by jessesquires** [comment]
Thanks for taking this @BasThomas ! 💯

**Comment by RomanVolkov** [comment]
https://swift.org/blog/xcode-9-1-improves-display-of-fatal-errors

**Comment by BasThomas** [comment]
https://twitter.com/olebegemann/status/917468701812838401

**Comment by BasThomas** [comment]
@RomanVolkov that's already in! :)

**Comment by BasThomas** [comment]
https://github.com/apple/swift-evolution/pull/753

**Comment by RomanVolkov** [comment]
@BasThomas oh, okay, great! :)

**Comment by BasThomas** [comment]
https://twitter.com/olebegemann/status/917710728194347009

**Comment by BasThomas** [comment]
https://github.com/apple/swift/pull/9619

**Comment by BasThomas** [comment]
https://gist.github.com/regexident/1b8e84974da2243e5199e760508d2d25

**Comment by BasThomas** [comment]
https://twitter.com/AirspeedSwift/status/918159453467295744

**Comment by BasThomas** [comment]
https://twitter.com/slava_pestov/status/918342575165120513
