### ISSUE TITLE
Writers for upcoming issues

### ISSUE THREAD

**Issue by jessesquires** [SwiftWeekly/swiftweekly.github.io#323]
Hey @SwiftWeekly/writers 😄 

I'm going to be out for the next few weeks while preparing for and attending conferences (iOS Singapore and try! Swift India). So, the next few issues from now through mid-November are up for grabs. 

If anyone is interested in taking one of these, please comment here so we can coordinate. I'll still be available to review and proofread, just not for making a whole issue.

> If an issue doesn't have a writer, no worries! We will skip it for that week.

### Upcoming issues

- ✅ ~~Oct 12,  Issue 91 - @BasThomas~~
- ✅ ~~Oct 19~~ **Let's skip this week.**
- ✅  ~~Oct 26, Issue 92 - @RomanVolkov~~
- ✅ ~~Nov 2, Issue 93 - @BasThomas~~
- ✅ ~~Nov 9, Issue 94 - @modocache~~
- Nov 16, Issue 95 - @modocache 
- Nov 23 — **No issue**, skip for Thanksgiving holiday in US 🦃 

### Sponsorships

I've paused sponsorships for now. However, if anyone wants or needs a sponsorship for their issue, then let me know and I can try to find a sponsor. This, of course, means I will be forwarding you the sponsorship fee 💰 to compensate you for your time and effort 😄. 

Having a sponsor also means **you are on the hook** for that issue. We must publish it and *it must* be high quality. 😄

**Comment by BasThomas** [comment]
I can take Nov 2. :)

**Comment by gregheo** [comment]
I'm following @jessesquires to Singapore and will try to get a selfie with him. That's worth a sponsorship isn't it?

**Comment by modocache** [comment]
I'd like to do November 9th and 16th.

**Comment by jessesquires** [comment]
Awesome 🥇 Thanks @BasThomas and @modocache ! 😄

**Comment by RomanVolkov** [comment]
I can take both Oct 19, Issue 92 and Oct 26, Issue 93

**Comment by jessesquires** [comment]
Updated main issue. I won't be able to review on Oct 19, so let's just skip that week, too. (Next week). Then we'll resume Oct 26. cc @RomanVolkov

**Comment by RomanVolkov** [comment]
@jessesquires ok
