### ISSUE TITLE
[92] Issue #92 - Oct 26, 2017

### ISSUE THREAD

**Issue by BasThomas** [SwiftWeekly/swiftweekly.github.io#325]
To contribute to this issue, simply leave a comment here. Please also review [our contributing guidelines](https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/CONTRIBUTING.md).

The current draft for this issue in [`_drafts/`](https://github.com/SwiftWeekly/swiftweekly.github.io/tree/master/_drafts). If you want to contribute directly, feel free to [open a pull request](https://github.com/SwiftWeekly/swiftweekly.github.io/compare?expand=1).

**Comment by BasThomas** [comment]
https://twitter.com/clattner_llvm/status/918885734890663937

**Comment by BasThomas** [comment]
https://github.com/apple/swift-evolution/issues/114

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
https://github.com/apple/swift/pull/9619#issuecomment-336746025

**Comment by BasThomas** [comment]
https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20171009/040362.html

**Comment by SD10** [comment]
https://swift.org/blog/swift-4-1-release-process/

**Comment by BasThomas** [comment]
https://twitter.com/slava_pestov/status/920477411535237121

**Comment by BasThomas** [comment]
https://twitter.com/slava_pestov/status/922357520819134465

**Comment by jessesquires** [comment]
@RomanVolkov - don't forget, we're publishing this thursday 😄

**Comment by RomanVolkov** [comment]
@jessesquires  don't worry, issue will be on time:)

**Comment by jessesquires** [comment]
https://github.com/apple/swift/pull/12598

**Comment by jessesquires** [comment]
Fixing regressions:
https://github.com/apple/swift/pull/12595

**Comment by BasThomas** [comment]
Ping @RomanVolkov - let me know if you need any help 👍

**Comment by BasThomas** [comment]
https://twitter.com/slava_pestov/status/923437365867061248

**Comment by RomanVolkov** [comment]
@BasThomas @jessesquires @SD10 thank you for all your links!
