### ISSUE TITLE
[93] Issue #93 - Nov 02, 2017

### ISSUE THREAD

**Issue by BasThomas** [SwiftWeekly/swiftweekly.github.io#328]
To contribute to this issue, simply leave a comment here. Please also review [our contributing guidelines](https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/CONTRIBUTING.md).

The current draft for this issue in [`_drafts/`](https://github.com/SwiftWeekly/swiftweekly.github.io/tree/master/_drafts). If you want to contribute directly, feel free to [open a pull request](https://github.com/SwiftWeekly/swiftweekly.github.io/compare?expand=1).

**Comment by BasThomas** [comment]
https://github.com/apple/swift-evolution/issues/754

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
https://store.apple.com/xc/de/vieworder/W568910935/bas.broek@live.nl/

**Comment by BasThomas** [comment]
https://twitter.com/slava_pestov/status/924133239568064514

**Comment by BasThomas** [comment]
https://twitter.com/slava_pestov/status/924133915199119360

**Comment by BasThomas** [comment]
https://github.com/apple/swift-evolution/issues/756

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jessesquires** [comment]
Potential for python inter-op
https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20171023/040733.html

**Comment by BasThomas** [comment]
Finally https://twitter.com/slava_pestov/status/924493935514230784

**Comment by jessesquires** [comment]
Seniors in Singapore learn Swift for “hour of code”

https://www.cnet.com/news/singapore-teaches-its-seniors-to-code/

**Comment by jessesquires** [comment]
must use this for "Finally"

https://twitter.com/jckarter/status/925122252479148032

**Comment by jessesquires** [comment]
"they read our blogs"
https://twitter.com/gregheo/status/925119320606236673

**Comment by BasThomas** [comment]
https://twitter.com/slava_pestov/status/925133908835835904

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RomanVolkov** [comment]
Might be interesting 
https://developer.ibm.com/swift/2017/10/30/kitura-20/

**Comment by BasThomas** [comment]
https://twitter.com/twostraws/status/924933983883931648

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jessesquires** [comment]
Final Xcode 9.1 released
https://developer.apple.com/news/releases/?id=10302017c
https://twitter.com/slava_pestov/status/925548115452497920

**Comment by BasThomas** [comment]
https://twitter.com/modocache/status/925555416351825920

**Comment by RomanVolkov** [comment]
I did not find any mentions about this document, maybe I missed it, but I think it's a great document to share.
https://github.com/apple/swift/blob/master/docs/OptimizationTips.rst

**Comment by BasThomas** [comment]
Hey @RomanVolkov - it seems like the document has been there [since before Swift was open sourced](https://github.com/apple/swift/commit/02b578b9aba0f25ce285d9728230356b0c34808b#diff-6551cd688c812cb4fdebcdb5b196a314); I have not put it in the weekly for now, as at least I think it isn't too time sensitive at this point.
