### ISSUE TITLE
[94] Issue #94 - Nov 09, 2017

### ISSUE THREAD

**Issue by BasThomas** [SwiftWeekly/swiftweekly.github.io#330]
To contribute to this issue, simply leave a comment here. Please also review [our contributing guidelines](https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/CONTRIBUTING.md).

The current draft for this issue in [`_drafts/`](https://github.com/SwiftWeekly/swiftweekly.github.io/tree/master/_drafts). If you want to contribute directly, feel free to [open a pull request](https://github.com/SwiftWeekly/swiftweekly.github.io/compare?expand=1).

**Comment by jessesquires** [comment]
Thanks @modocache for taking this issue! 🎉

**Comment by modocache** [comment]
awww yissss

**Comment by jessesquires** [comment]
It finally happened 
https://github.com/apple/swift-evolution/pull/757

**Comment by BasThomas** [comment]
https://github.com/apple/swift-evolution/pull/757#issuecomment-341838593

**Comment by jessesquires** [comment]
llbuild, build cancellation
https://github.com/apple/swift-llbuild/pull/195

**Comment by RomanVolkov** [comment]
https://twitter.com/slava_pestov/status/927345989270224897

**Comment by BasThomas** [comment]
https://github.com/apple/swift-evolution/pull/760

**Comment by RomanVolkov** [comment]
https://github.com/apple/swift/pull/12682

**Comment by jessesquires** [comment]
Reviving the proposal for deriving enum cases for `MyEnum.allCases`. This was very popular around ~Swift 3 but never made the cut. Potentially could be in Swift 5.
https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20171106/040950.html

**Comment by jessesquires** [comment]
https://github.com/apple/swift-evolution/pull/761

**Comment by modocache** [comment]
I updated the draft at #331. Can someone confirm I'm understanding the IUO pull request correctly?

**Comment by jpsim** [comment]
[[swift-corelibs-dev] Latest CoreFoundation import from High Sierra](https://lists.swift.org/pipermail/swift-corelibs-dev/Week-of-Mon-20171106/001324.html)

and PR: https://github.com/apple/swift-corelibs-foundation/pull/1305

**Comment by jessesquires** [comment]
coroutines in SIL
https://github.com/apple/swift/pull/12789

**Comment by jessesquires** [comment]
swift build time tips
https://github.com/fastred/Optimizing-Swift-Build-Times

**Comment by BasThomas** [comment]
SE-0187 is under review

**Comment by modocache** [comment]
FYI I'll get a finished draft of #331 done tonight around 10PM or 11PM eastern time, and then I'll ping this thread. I'd definitely appreciate some feedback at that point. I'll merge the pull request around 12:30PM eastern time tomorrow.

**Comment by modocache** [comment]
OK, I think the body of this week's issue is pretty much done in my eyes, please feel free to review it at #331. I'm also very open to suggestions on the intro and outro.

**Comment by jpsim** [comment]
Eliminating IndexDistance: https://twitter.com/AirspeedSwift/status/928376958357876736

**Comment by BasThomas** [comment]
188 in review, too

**Comment by modocache** [comment]
Done, and done!

**Comment by modocache** [comment]
I pushed #331 so issue 94 should be good to go. If anyone has any last-minute edits please open a pull request. Issue 95 notes can be found on #335.

**Comment by BasThomas** [comment]
Awesome issue, @modocache! 😀

**Comment by modocache** [comment]
Thank you! Thanks for all the feedback & editing.

**Comment by modocache** [comment]
Email seemed to have gone out, LGTM.
