### ISSUE TITLE
Re-enable danger if we can make it useful

### ISSUE THREAD

**Issue by jessesquires** [SwiftWeekly/swiftweekly.github.io#333]
See #332 and https://github.com/SwiftWeekly/swiftweekly.github.io/pull/331#issuecomment-341521265.

Would be nice if danger-prose actually worked as advertised.

**Comment by modocache** [comment]
- The ability to add words to an ignore list would be awesome.
- We'd also want some words to have a canonical spelling (for example, does the compiler suggest "fixits" or "fix-its"? Do we invoke the compiler on the "command line", "commandline", or "command-line"?).
- We need the bot to be able to recognize Liquid `{% tag syntax %}`.
