### ISSUE TITLE
[95] Issue #95 - Nov 16, 2017

### ISSUE THREAD

**Issue by modocache** [SwiftWeekly/swiftweekly.github.io#335]

**Comment by gregheo** [comment]
[meta] Update on move to Discourse forums
https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20171106/041091.html

**Comment by jessesquires** [comment]
IRGen for conditional conformances
https://github.com/apple/swift/pull/12531

**Comment by BasThomas** [comment]
https://twitter.com/jckarter/status/928733395219185664 / https://github.com/apple/swift/pull/6485 is back

**Comment by BasThomas** [comment]
https://twitter.com/slava_pestov/status/928834964690411520 + thread

**Comment by BasThomas** [comment]
https://github.com/apple/swift-evolution/pull/764 / https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20171023/040652.html

**Comment by BasThomas** [comment]
https://twitter.com/slava_pestov/status/928902232468156416

**Comment by modocache** [comment]
https://twitter.com/arekholko/status/928964586396581889

**Comment by BasThomas** [comment]
https://github.com/apple/swift-package-manager/pull/1390

**Comment by modocache** [comment]
The last issue mentioned the `-Ounchecked` thread but the discussion is now centered on whether command-line Swift options need to go through swift-evolution in some cases. It's an interesting topic that I think I'll expand on in this issue. (Just for convenience, here's a link to one message in the mailing list thread: https://lists.swift.org/pipermail/swift-dev/Week-of-Mon-20171113/005944.html)

**Comment by modocache** [comment]
New Swift Unwrapped: https://spec.fm/podcasts/swift-unwrapped/94819

**Comment by modocache** [comment]
Many people (myself included) have tried to refactor Swift's Python `build-script`, and this looks like the latest development on that front: https://github.com/apple/swift/pull/12873

**Comment by modocache** [comment]
A fix for one of the starter tasks in last week's issue: https://github.com/apple/swift/pull/12856/

**Comment by modocache** [comment]
Would've been nice to include this last week, but I'll do it this week instead: https://lists.swift.org/pipermail/swift-dev/Week-of-Mon-20171106/005828.html

**Comment by BasThomas** [comment]
https://twitter.com/slava_pestov/status/930260260362772480

**Comment by RomanVolkov** [comment]
https://github.com/apple/swift/pull/12910

**Comment by modocache** [comment]
https://twitter.com/Injection4Xcode/status/930125224233914376

**Comment by BasThomas** [comment]
189 in review

**Comment by BasThomas** [comment]
https://twitter.com/clattner_llvm/status/930832426548436992

**Comment by BasThomas** [comment]
187 accepted, review extended to bikshed on naming: https://github.com/apple/swift-evolution/commit/2d24b0ce9f138858b8341467170d6d8ba973827f

**Comment by BasThomas** [comment]
https://twitter.com/tkremenek/status/930975883027820545

**Comment by BasThomas** [comment]
https://twitter.com/slava_pestov/status/930976398792994816

**Comment by modocache** [comment]
Draft of this week's issue here: https://github.com/SwiftWeekly/swiftweekly.github.io/pull/336

**Comment by kud1ing** [comment]
Alexander Lash:
> My team is planning to contribute to lib/Syntax - we're interested in linting, formatting, and refactoring.
https://twitter.com/lexlash/status/930877904551944192

**Comment by modocache** [comment]
Published. Thanks everybody! I pushed a draft for issue 96, which according to #323 is next next week. I assume it'll be written by @jessesquires...? Here are the notes for that issue: #338.
