### ISSUE TITLE
[96] Issue #96 - Nov 30, 2017 

### ISSUE THREAD

**Issue by modocache** [SwiftWeekly/swiftweekly.github.io#338]
To contribute to this issue, simply leave a comment here. Please also review [our contributing guidelines](https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/CONTRIBUTING.md).

The current draft for this issue in [`_drafts/`](https://github.com/SwiftWeekly/swiftweekly.github.io/tree/master/_drafts). If you want to contribute directly, feel free to [open a pull request](https://github.com/SwiftWeekly/swiftweekly.github.io/compare?expand=1).

**Comment by BasThomas** [comment]
https://twitter.com/slava_pestov/status/931365736005505024

**Comment by BasThomas** [comment]
190 in review

**Comment by RomanVolkov** [comment]
https://twitter.com/tkremenek/status/930975883027820545

**Comment by BasThomas** [comment]
@RomanVolkov can you check if it wasn’t already added in the previous issue? https://github.com/SwiftWeekly/swiftweekly.github.io/issues/335#issuecomment-344817396

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by modocache** [comment]
https://github.com/apple/swift-llbuild/pull/200

**Comment by RomanVolkov** [comment]
@BasThomas no, it's not at result #95 issue

**Comment by jpsim** [comment]
Python Interop with Swift 4+: https://lists.swift.org/pipermail/swift-evolution//Week-of-Mon-20171113/041463.html

**Comment by gregheo** [comment]
Would like to submit this animated GIF I lovingly hand-crafted for consideration:
https://twitter.com/gregheo/status/933429621399289856

**Comment by jpsim** [comment]
Fix [SR-6290](https://bugs.swift.org/browse/SR-6290), Swift dictionary padding with enum keys: https://github.com/apple/swift-lldb/pull/259

**Comment by jessesquires** [comment]
Fushia OS
https://github.com/apple/swift/pull/12955

Conditional conformances
https://github.com/apple/swift/pull/13046

[Syntax] improvements
https://github.com/apple/swift/pull/12989

[AST] optimizations
https://github.com/apple/swift/pull/13041

**Comment by skyweb07** [comment]
Hey guys, I'm making this Snapshot test library to replace the Facebook deprecated one `FBSnapshotTestCase`, it would be nice to get into the list https://github.com/skyweb07/Snap.swift thanks :)

**Comment by BasThomas** [comment]
Hey @skyweb07. The library is looking awesome! That being said, Swift Weekly Brief focuses on what's happening in the swift.org projects, so I'm not sure this would be suited for the Swift Weekly audience.

**Comment by skyweb07** [comment]
thanks @BasThomas, I did thought it was a general weekly, thanks anyway, keep the good work guys!! cheers!

**Comment by RomanVolkov** [comment]
@skyweb07 I think you confused this digest with this one http://digest.swiftweekly.com/
I think they will be glad to your library:)

**Comment by modocache** [comment]
Another article in my series on the Swift compiler internals, in case you guys'd like to include it -- this one is a walkthrough of the code in the Swift driver: https://modocache.io/reading-and-understanding-the-swift-driver-source-code

**Comment by jessesquires** [comment]
Finally
https://twitter.com/jckarter/status/934867063721541632

**Comment by BasThomas** [comment]
Dynamic Member Lookup: https://github.com/apple/swift-evolution/pull/768

**Comment by jessesquires** [comment]
https://github.com/apple/swift/pull/13062

https://github.com/apple/swift/pull/13007

**Comment by gregheo** [comment]
[SE-0191](https://github.com/apple/swift-evolution/blob/master/proposals/0191-eliminate-indexdistance.md) "Eliminate IndexDistance from Collection" is under review

https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20171127/041716.html

**Comment by BasThomas** [comment]
https://github.com/apple/swift-evolution/pull/771

**Comment by BasThomas** [comment]
190 accepted, 188 accepted

**Comment by BasThomas** [comment]
https://twitter.com/dgregor79/status/935993438687731713
