### ISSUE TITLE
Question on integrating with MailChimp

### ISSUE THREAD

**Issue by ColinEberhardt** [SwiftWeekly/swiftweekly.github.io#339]
Hi All - firstly, a big 'thank you' for publishing this with a CC licence - it made it really quick and easy for me to put together my new newsletter (http://wasmweekly.news/). 

I've got a quick question that I hope you'll be able to help out with. I'm using mailchimp to email the subscribers, which I believe is the same process as yourselves. Ths means that my workflow is a bit repetitive:

1. Create each issue in MailChimp using their online editor
2. Replicate on the website using markdown.

I haven't managed to find a way to author the issues in a single place, e.g. markdown to mailchimp conversion.

Have you managed to find a good way to avoid creating the same content in two different formats / locations?

Thank you!

**Comment by BasThomas** [comment]
As far as I know this process is automated for Swift Weekly Brief. @jessesquires should know more about it.

Also, congrats on your newsletter! 🎉

**Comment by gregheo** [comment]
Hi @ColinEberhardt! I believe we're using MailChimp's RSS-to-email feature: https://mailchimp.com/features/rss-to-email/

**Comment by ColinEberhardt** [comment]
Brilliant, thanks @gregheo - I hadn't thought of that. This will certainly make my life simpler 💯

**Comment by jessesquires** [comment]
Hey @ColinEberhardt ! 👋 😄 

Awesome to hear. Newsletter looks good! 

@gregheo is correct, we're using the RSS-to-email. Then, I automate tweets using IFTTT which also has [RSS hooks](https://ifttt.com/feed). With this + GH Pages hosting, all we need to do each with is merge some markdown and everything else happens automatically. ✨ 

Let me know if you have any other questions! 😊 

Also, sorry to chime in late (been traveling).

**Comment by ColinEberhardt** [comment]
Thanks @jessesquires - really appreciate the help from you all, it's been a big help :-)
