### ISSUE TITLE
[100] Issue #100 - Jan 04, 2018

### ISSUE THREAD

**Issue by jessesquires** [SwiftWeekly/swiftweekly.github.io#345]
To contribute to this issue, simply leave a comment here. Please also review [our contributing guidelines](https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/CONTRIBUTING.md).

The current draft for this issue in [`_drafts/`](https://github.com/SwiftWeekly/swiftweekly.github.io/tree/master/_drafts). If you want to contribute directly, [open a pull request](https://github.com/SwiftWeekly/swiftweekly.github.io/compare?expand=1).

**Comment by BasThomas** [comment]
100! 🎉😎

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gregheo** [comment]
Issue 100 deserves a sonnet rather than a limerick.

**Comment by kud1ing** [comment]
[Refactoring: Expand a ternary operator into an if statement and vice-versa](https://github.com/apple/swift/pull/12554) got merged.

**Comment by jessesquires** [comment]
changing from Dec 28 to Jan 4 😄

**Comment by jessesquires** [comment]
https://duan.ca/2017/12/23/contributing-to-open-source-foundation/

**Comment by RomanVolkov** [comment]
SE-0192 returned for revision https://github.com/apple/swift-evolution/pull/777
