### ISSUE TITLE
Trial Run [101] Issue #101 - Jan 18, 2018

### ISSUE THREAD

**Issue by tapthaker** [SwiftWeekly/swiftweekly.github.io#346]
To contribute to this issue, simply leave a comment here. Please also review [our contributing guidelines](https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/CONTRIBUTING.md).

The current draft for this issue in the Pull Request.

**Comment by jessesquires** [comment]
Awesome! 🎉 Thanks @tapthaker ! 

@SwiftWeekly/writers -- Tapan is interested in joining / helping resume the newsletter with @BasThomas and @RomanVolkov. We're going to do a trial run for this issue to bring Tapan up to speed (but not publish the issue).

**Comment by tapthaker** [comment]
@jessesquires Thanks for introducing me. I am going to start writing the draft. Folks please help out with updates for this week as and when possible.

**Comment by tapthaker** [comment]
I think we should cover [Conditional conformance](https://swift.org/blog/conditional-conformance/) even if it truly isn't a part of this week.

**Comment by BasThomas** [comment]
Awesome @tapthaker! Looking forward. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
Here are some URLs I gathered:

https://twitter.com/SwiftLang/status/950448534599315456
https://twitter.com/AirspeedSwift/status/950446966126751744
194 in review
https://github.com/apple/swift-evolution/pull/781

https://twitter.com/Ilseman/status/951181851229483008

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RomanVolkov** [comment]
@tapthaker Nice to meet you!

**Comment by RomanVolkov** [comment]
SE-0192 updates: https://github.com/apple/swift-evolution/pull/777

**Comment by RomanVolkov** [comment]
Proposal update: Deriving collections of enum cases - https://github.com/apple/swift-evolution/pull/114#issuecomment-354573721
SE-0192 revision: https://github.com/apple/swift-evolution/pull/777

**Comment by jessesquires** [comment]
"Finally" 
https://twitter.com/jckarter/status/951199675163422720

**Comment by RomanVolkov** [comment]
https://github.com/apple/swift/pull/13893
https://github.com/apple/swift/pull/13897

**Comment by RomanVolkov** [comment]
“Finally”
https://twitter.com/jckarter/status/951569237318893568

**Comment by BasThomas** [comment]
SE-0192 returned for revision: https://github.com/apple/swift-evolution/commit/25ec3030b7b656e5d7df7c150ab6f53723cdc0a2

**Comment by BasThomas** [comment]
Bool toggle proposal: https://github.com/apple/swift-evolution/pull/782

**Comment by RomanVolkov** [comment]
Improvements to function's calling convention
https://github.com/apple/swift/pull/13935

**Comment by tapthaker** [comment]
Hey folks, apologies for not continuing to update the PR. I was a bit ill. I will be updating in the next couple of hours.

**Comment by jessesquires** [comment]
Bool-toggle blog post: https://www.objc.io/blog/2018/01/16/toggle-extension-on-bool/

**Comment by RomanVolkov** [comment]
https://twitter.com/slava_pestov/status/953473190226833408

**Comment by BasThomas** [comment]
https://twitter.com/ericasadun/status/953655632552316929

**Comment by RomanVolkov** [comment]
Small step with huge background and importance 
https://github.com/apple/swift/pull/13573/files

**Comment by tapthaker** [comment]
I like the idea of
One small step for resilience, one giant step for ABI

**Comment by jessesquires** [comment]
Alright folks -- thanks everyone for helping with this exercise! See the practice issue at #347. 

More discussion on the future of the newsletter at #348 😄 🎉

**Comment by tapthaker** [comment]
Thanks @jessesquires for this exercise! It was an amazing experience indeed.
Special thanks to @BasThomas @RomanVolkov for helping me with several updates & reviewing the blog along the way
