### ISSUE TITLE
[101] Issue #101 - Jan 25, 2018

### ISSUE THREAD

**Issue by jessesquires** [SwiftWeekly/swiftweekly.github.io#348]
To contribute to this issue, simply leave a comment here. Please also review [our contributing guidelines](https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/CONTRIBUTING.md).

The current draft for this issue in [`_drafts/`](https://github.com/SwiftWeekly/swiftweekly.github.io/tree/master/_drafts). If you want to contribute directly, [open a pull request](https://github.com/SwiftWeekly/swiftweekly.github.io/compare?expand=1).

**Comment by jessesquires** [comment]
Hey everyone —

I've talked with @BasThomas about taking over the newsletter and he's excited to do it. 🎉 

He's going to bring it back with Issue 101 next week.

After me, he's written the most issues and was one of the earliest external contributors. Out of the contributors who had the capacity to keep this going, he has the most experience, so he's going to be taking the lead moving forward. (I'll still be around, but increasingly hands-off.) We're also going to move to a bi-weekly (every other week) schedule. Given this, it makes the most sense for him to re-introduce the newsletter with Issue 101. 😄 

I'll be working on updating some copy, etc. on the site this weekend, as well as some of the other open issues.

After the "re-launch" next week, we can start rotating authors as needed. Bas will probably be writing most to kick us off, but I'll let him decide. 😄 

Perhaps @tapthaker could take 102 as his first public issue? 😊

**Comment by tapthaker** [comment]
Awesome !!! Looking forward to working with you all.

**Comment by SD10** [comment]
@BasThomas If you need any help with things like proofreading, don't hesitate to ping me! 👍

**Comment by jessesquires** [comment]
@SD10 if you'd like to be more formally involved, let us know. 😄 If you're interested in writing issues every once in a while, that'd be a huge help.

**Comment by SD10** [comment]
@jessesquires I'm interested but I have a bad habit of offering to do everything and over-extending myself 😅 If I free up another obligation I will focus some time here for sure!

**Comment by BasThomas** [comment]
Haha, that's some great self-reflection @SD10. Feel free to hop in when you feel like it (you know where to find the drafts). Would be super appreciated, but no obligations of course :)

**Comment by BasThomas** [comment]
https://twitter.com/mishaldshah/status/954463395083730944

**Comment by BasThomas** [comment]
https://twitter.com/ericasadun/status/954746199415795713

**Comment by jessesquires** [comment]
@BasThomas - just pushed the draft template for you 😄

**Comment by jessesquires** [comment]
https://forums.swift.org/t/welcome-to-the-swift-forums/8

**Comment by BasThomas** [comment]
https://swift.org/blog/forums/

**Comment by jessesquires** [comment]
this is pretty good. see joe groff's answer.
https://twitter.com/twostraws/status/954709346679754755

**Comment by BasThomas** [comment]
https://github.com/apple/swift-evolution/pull/783

**Comment by SD10** [comment]
https://github.com/apple/swift/pull/14041
https://twitter.com/jckarter/status/955642158190489601

**Comment by BasThomas** [comment]
https://twitter.com/jckarter/status/955642158190489601

**Comment by BasThomas** [comment]
https://twitter.com/tkremenek/status/955862433171517440

**Comment by jessesquires** [comment]
hey folks -- had ☕️ with @timothymiko today. he wants to start helping out and eventually try writing an issue. say hi 👋

**Comment by SD10** [comment]
that must’ve been some really good ☕️ 🤣 welcome @timothymiko!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by timothymiko** [comment]
hey everyone, excited to help contribute!

**Comment by BasThomas** [comment]
Awesome @timothymiko 🙌

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SD10** [comment]
I thought this would be good for a wrap up joke 🤣 
https://twitter.com/jckarter/status/955931838320492544

**Comment by BasThomas** [comment]
https://twitter.com/dgregor79/status/956024038572396546

**Comment by BasThomas** [comment]
196 in review https://twitter.com/tkremenek/status/956069563304759296

**Comment by jessesquires** [comment]
Joe's talk from Swift Summit posted:
https://www.skilled.io/u/swiftsummit/swift-s-reflective-underpinnings-joe-groff

**Comment by jessesquires** [comment]
Xcode 9.3 beta with Swift 4.1

https://download.developer.apple.com/Developer_Tools/Xcode_9.3_beta/Release_Notes_for_Xcode_9.3_beta.pdf

**Comment by jessesquires** [comment]
Final playgrounds 2.0 for iPad 

https://developer.apple.com/news/?id=01242018a

**Comment by jessesquires** [comment]
https://github.com/apple/swift/commit/a10a715c02d8d7161420397ed1188d80816da97e

**Comment by BasThomas** [comment]
https://twitter.com/TimTr/status/956253973148676096

**Comment by jessesquires** [comment]
🎉💪

**Comment by SD10** [comment]
Congrats on the first new issue @BasThomas 🔥🔥🔥

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tapthaker** [comment]
Congratulations @BasThomas !!

**Comment by BasThomas** [comment]
Thanks @SD10 & @tapthaker. 😊
