### ISSUE TITLE
Address potential security vulnerability in nokogiri

### ISSUE THREAD

**Issue by jessesquires** [SwiftWeekly/swiftweekly.github.io#350]
Wow. another new useful github feature:

![screen shot 2018-01-18 at 9 44 04 am](https://user-images.githubusercontent.com/2301114/35112826-253b1bd8-fc34-11e7-9c14-ca8c18d3b522.png)

Probably just need to `bundle update`

**Comment by BasThomas** [comment]
Tried, but it seems like a lower (1.4) version of nokogiri is required by another dependency :(

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jessesquires** [comment]
Ugh. 😢  Did you update GH-pages to the latest version?

**Comment by BasThomas** [comment]
Haven’t tried, no. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
