### ISSUE TITLE
[102] Issue #102 - Feb 8, 2018

### ISSUE THREAD

**Issue by BasThomas** [SwiftWeekly/swiftweekly.github.io#361]
To contribute to this issue, simply leave a comment here. Please also review [our contributing guidelines](https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/CONTRIBUTING.md).

The current draft for this issue in [`_drafts/`](https://github.com/SwiftWeekly/swiftweekly.github.io/tree/master/_drafts). If you want to contribute directly, [open a pull request](https://github.com/SwiftWeekly/swiftweekly.github.io/compare?expand=1).

**Comment by BasThomas** [comment]
https://swiftunboxed.com/lang/conditional-conformance/

**Comment by BasThomas** [comment]
197 in review: https://github.com/apple/swift-evolution/blob/master/proposals/0197-remove-where.md

**Comment by tapthaker** [comment]
@BasThomas : That was fast !!! 197 just made it to review !!!

**Comment by BasThomas** [comment]
🏎💨

**Comment by tapthaker** [comment]
@BasThomas: I couldn't be active last week. Do you want me to take up the ownership of the article this week ?

**Comment by BasThomas** [comment]
No worries at all! If you want to write the next issue, go for it! As we’re publishing every other week, it will be the issue for February 8th. Is that OK with you?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tapthaker** [comment]
Yes, it is fine with me.

**Comment by BasThomas** [comment]
Can you check again if you got the invite for the organisation and accept that? Then I can also assign you as an assignee to this issue :)

**Comment by tapthaker** [comment]
Haven't got the invite. Checked everywhere. Please send it again.

**Comment by BasThomas** [comment]
<img width="468" alt="screen shot 2018-01-26 at 11 53 58" src="https://user-images.githubusercontent.com/4190298/35436678-a679b298-028f-11e8-8a8b-a1cefdfd7bef.png">
You really should've been invited, I think Jesse and I already tried several times. 😁
Do you not see a button at https://github.com/swiftweekly? Can you send a screenshot of that page maybe?

**Comment by tapthaker** [comment]
Joined. My bad.

**Comment by jessesquires** [comment]
@tapthaker 🎉 you should go ahead and generate the draft 😊

**Comment by tapthaker** [comment]
milseman is on fire with String guts

https://github.com/apple/swift/pull/14186

**Comment by BasThomas** [comment]
“Removing terminology” is almost always good https://github.com/apple/swift/pull/14227
https://twitter.com/slava_pestov/status/957720067822706688

**Comment by tapthaker** [comment]
Was thinking of mentioning about tryswift.
https://www.tryswift.co/events/2018/tokyo/en/

**Comment by tapthaker** [comment]
https://twitter.com/SwiftSummit/status/955935679288041472

**Comment by tapthaker** [comment]
https://pspdfkit.com/blog/2018/binary-frameworks-swift/

**Comment by tapthaker** [comment]
Update: I know I haven't been writing & keeping draft up-to-date. I will ensure that it is updated by EOD tomorrow

**Comment by SD10** [comment]
@tapthaker I'm not that active around here but from what I can remember the drafts were sometimes done a couple days before. You have a ton of time to collect resources until then!

**Comment by BasThomas** [comment]
> Was thinking of mentioning about tryswift.
> https://www.tryswift.co/events/2018/tokyo/en/

try! Swift is awesome, but I am not so sure how it would be related to the Weekly Brief. Maybe we can share some presentations that focussed on Swift.org and its project afterwards?

> https://twitter.com/SwiftSummit/status/955935679288041472

This has already been mentioned in [issue 101](https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/_posts/2018-01-25-issue-101.md#news-and-community)!

> Update: I know I haven't been writing & keeping draft up-to-date. I will ensure that it is updated by EOD tomorrow

No worries! Looking forward to see a draft with the first things in it 😊

**Comment by alexito4** [comment]
Hi! First time here ^^
I found <https://www.skilled.io/u/swiftsummit/creating-refactoring-transformations-for-swift> interesting. Would be nice to help get more attraction to the refactoring tools 👍

**Comment by BasThomas** [comment]
Hi @alexito4 👋, thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RomanVolkov** [comment]
[Proposal] Replace PlaygroundQuickLook/CustomPlaygroundQuickLookable with new API: https://github.com/apple/swift-evolution/pull/784

**Comment by BasThomas** [comment]
https://twitter.com/pointfreeco/status/958103863428632576

**Comment by RomanVolkov** [comment]
https://github.com/apple/swift/pull/14296

**Comment by jessesquires** [comment]
Conditional conformance to `Hashable`

https://github.com/apple/swift/pull/14247

**Comment by BasThomas** [comment]
https://twitter.com/SwiftSummit/status/958815695600365568

**Comment by BasThomas** [comment]
Finally: https://twitter.com/jckarter/status/959091909129113602

**Comment by BasThomas** [comment]
198 in review https://github.com/apple/swift-evolution/pull/784

**Comment by BasThomas** [comment]
195 review extended https://github.com/apple/swift-evolution/commit/f1ef59909b8f6bad7ba0f85152ca294d0b310638

**Comment by BasThomas** [comment]
https://twitter.com/dgregor79/status/959213417964781568

**Comment by BasThomas** [comment]
197 approved

**Comment by jpsim** [comment]
CountableRange removed: https://twitter.com/dgregor79/status/959466959388553216

**Comment by BasThomas** [comment]
Conditional Conformance implemented. That's a big part of ABI Stability: https://github.com/apple/swift-evolution/commit/3bccceedbe9085c5e1a7e79d8a6cf2bfaa06d476

**Comment by jessesquires** [comment]
Before, we would periodically link to the proposal status page.

I think we should regularly link to this new forum page now:
https://forums.swift.org/c/evolution/proposal-reviews

With something like: "Here are the current proposals under review" and try to encourage readers to participate.

**Comment by BasThomas** [comment]
Yes, I think that would be a good idea now that it is easier than ever to do so. Also saw the tweet already - thanks!

**Comment by tapthaker** [comment]
Agreed. I will make the changes accordingly.

**Comment by BasThomas** [comment]
Awesome, thanks @tapthaker!

Let me know if I can help you with something - we're getting closer to publishing this Thursday 😃

**Comment by BasThomas** [comment]
https://twitter.com/harlanhaskins/status/959926493190279168

**Comment by tapthaker** [comment]
@BasThomas : Thanks. I will be able to get things done on time.

**Comment by tapthaker** [comment]
I have a feeling that Bi-Weekly issues are getting long. Just worried that excessive content might overwhelm the readers. Either that or I am writing more than necessary.

**Comment by jessesquires** [comment]
@tapthaker If that's the case, we should trim to only the most important things 😊 We can help / discuss on the PR.

**Comment by RomanVolkov** [comment]
I agree with both of you @jessesquires @tapthaker It's a great idea to focus only on major news.
but the situation can be with outdated news. E.g., something important happens after new issue and it will take 2 weeks to get informed.
@jessesquires @BasThomas is it an issue from your perspective or not?

**Comment by BasThomas** [comment]
I think for those cases (which I feel are quite rare - please let me / us know if you have any!) we can send a separate tweet.

If it does turn out that the biweekly schedule doesn’t work, we can look into solving it in some way at that point.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by modocache** [comment]
Shameless plug: is it too late to include a link to https://modocache.io/the-swift-frontend-lexing-and-parsing ?

**Comment by tapthaker** [comment]
@modocache : Thanks. I will be able to this for sure.
Just need someone up to review its @BasThomas ?

**Comment by BasThomas** [comment]
Go ahead :)

**Comment by jessesquires** [comment]
Hey @tapthaker -- not sure what happened with your intro comments on the PR. Sorry about that 😊 If you had some changes locally that you forgot to push, please open a new PR to add them 😄

**Comment by tapthaker** [comment]
`git push` failed for some reason but i didn't notice it. Creating a new PR

**Comment by tapthaker** [comment]
@BasThomas @jessesquires: Just added @modocache's article in the PR. Don't want to change intro comments now that it is out.
