### ISSUE TITLE
[104] Issue #104 - March 8, 2018

### ISSUE THREAD

**Issue by RomanVolkov** [SwiftWeekly/swiftweekly.github.io#362]
To contribute to this issue, simply leave a comment here. Please also review [our contributing guidelines](https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/CONTRIBUTING.md).

The current draft for this issue in [`_drafts/`](https://github.com/SwiftWeekly/swiftweekly.github.io/tree/master/_drafts). If you want to contribute directly, [open a pull request](https://github.com/SwiftWeekly/swiftweekly.github.io/compare?expand=1).

**Comment by BasThomas** [comment]
Created a draft for you @RomanVolkov :)

**Comment by mackoj** [comment]
https://github.com/apple/swift-clang/commit/334f080ab3c1bfbb13601a4f404b9c97e2294eb9

**Comment by jessesquires** [comment]
https://github.com/apple/swift/pull/14442

**Comment by jessesquires** [comment]
Jordan Rose blog post
http://belkadan.com/blog/2018/02/Many-to-Many-Protocols/

**Comment by tapthaker** [comment]
https://twitter.com/ericasadun/status/968705706777042944

https://forums.swift.org/t/accepted-se-198-playground-quicklook-api-revamp/10401

**Comment by RomanVolkov** [comment]
@BasThomas  thanks!

**Comment by BasThomas** [comment]
https://github.com/apple/swift-evolution/issues/794

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mackoj** [comment]
https://forums.developer.apple.com/thread/97662

**Comment by mackoj** [comment]
https://github.com/apple/swift/pull/14854

**Comment by BasThomas** [comment]
Thanks for sharing these @mackoj!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
https://twitter.com/Catfish_Man/status/968567431835795457

This (from @ilseman) is probably the Swift change I’m most excited about this year. Still a ways to go, but look at those delicious 2.5x ObjC bridging speedups even on this relatively early version! https://github.com/apple/swift/pull/14755

**Comment by BasThomas** [comment]
198 accepted: https://github.com/apple/swift-evolution/commit/6591496881319b749d4503a748317aedcd5be46a

**Comment by jessesquires** [comment]
Community reports of improved build times with Xcode 9.3 beat 3

https://twitter.com/benasher44/status/968905975724892160
https://twitter.com/adellibovi/status/969012500682477568

**Comment by BasThomas** [comment]
https://github.com/apple/swift-nio

**Comment by BasThomas** [comment]
Swift 4.2: https://github.com/apple/swift-evolution/pull/795

**Comment by mackoj** [comment]
https://download.developer.apple.com/Developer_Tools/Xcode_9.3_beta_3/Release_Notes_for_Xcode_9.3_beta_3.pdf

## Testing

xccov is a new command-line utility for inspecting the contents of Xcode coverage reports. It can be used to view coverage data in both human-readable and machine parseable format. See the man page for more information about the tool (man xccov). (37172926)

**Comment by jessesquires** [comment]
Also, regarding `swift-nio` (which @BasThomas linked above), they're using GH issues, not JIRA:
https://github.com/apple/swift-nio/issues (just interesting to note)

**Comment by jessesquires** [comment]
hey @RomanVolkov 👋 Do you want to try to get a draft going soon? 😄

**Comment by BasThomas** [comment]
@mackoj I covered `xccov` in issue 103 already. :)

**Comment by mackoj** [comment]
@BasThomas sorry I forgot about it :/

**Comment by mackoj** [comment]
https://github.com/apple/swift/pull/14913

**Comment by SD10** [comment]
Community: [First Class Swift API for Objective-C Frameworks](https://pspdfkit.com/blog/2018/first-class-swift-api-for-objective-c-frameworks/)

**Comment by RomanVolkov** [comment]
@jessesquires  yeah. I'll make first draft soon. Just had a crazy week after week of snowboarding and broken arm:) will start soon

**Comment by BasThomas** [comment]
Oh noes! If you do need any help, feel free to let me know.

**Comment by jessesquires** [comment]
Oh man. Sorry @RomanVolkov ! Get well soon 😊

**Comment by jessesquires** [comment]
Update on SE 192
https://forums.swift.org/t/se-0192-non-exhaustive-enums/7291/337

**Comment by RomanVolkov** [comment]
@BasThomas @jessesquires thank you guys:)

**Comment by tapthaker** [comment]
@RomanVolkov: Were you snowboarding swiftly ? Get well soon :)

**Comment by RomanVolkov** [comment]
@tapthaker yes:) just had bad braking from the top

**Comment by RomanVolkov** [comment]
@SwiftWeekly/writers Sorry about that, but seems I won't be able to make a good issue this time. Broken arm after traveling kicked me off of regular rhythm and past days were very chaotic. If anyone can handle this one - that will be great. I pushed new branch, but it has very few changes, just the list of started tasks (which is bigger that usual). 
Sorry again for late news

**Comment by BasThomas** [comment]
No worries - I can take over if no one else wants to :)

**Comment by RomanVolkov** [comment]
@BasThomas thanks a lot! Hope will make another issue soon)

**Comment by BasThomas** [comment]
Xcode 9 beta 4: https://download.developer.apple.com/Developer_Tools/Xcode_9.3_beta_4/Release_Notes_for_Xcode_9.3_beta_4.pdf

**Comment by tapthaker** [comment]
Take care @RomanVolkov . @BasThomas : let me know if I can help. We can split work amongst ourselves if need be.

**Comment by jessesquires** [comment]
fun trivia from Doug Gregor:
https://twitter.com/dgregor79/status/970857272724172800

**Comment by jessesquires** [comment]
Thanks @RomanVolkov ! Get well! 🤒

**Comment by BasThomas** [comment]
Thanks @tapthaker! Feel free to commit directly to the branch. 😊

**Comment by BasThomas** [comment]
https://twitter.com/ericasadun/status/970754573609484288

**Comment by tapthaker** [comment]
@BasThomas I will take up **Commits & Pull Requests** & **Proposals**.

**Comment by jessesquires** [comment]
@tapthaker if you don't mind, just make your edits directly on the existing PR #371 😄

**Comment by BasThomas** [comment]
194 accepted with revisions (https://github.com/apple/swift-evolution/pull/798)
