### ISSUE TITLE
[103] Issue #103 - Feb 22, 2018

### ISSUE THREAD

**Issue by jessesquires** [SwiftWeekly/swiftweekly.github.io#368]
To contribute to this issue, simply leave a comment here. Please also review [our contributing guidelines](https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/CONTRIBUTING.md).

The current draft for this issue in [`_drafts/`](https://github.com/SwiftWeekly/swiftweekly.github.io/tree/master/_drafts). If you want to contribute directly, [open a pull request](https://github.com/SwiftWeekly/swiftweekly.github.io/compare?expand=1).

**Comment by BasThomas** [comment]
https://github.com/apple/swift-evolution/pull/786

**Comment by tapthaker** [comment]
https://twitter.com/jckarter/status/961817885487259650

**Comment by SD10** [comment]
https://twitter.com/tkremenek/status/961865163568693248

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jessesquires** [comment]
https://swift.org/blog/osize/

**Comment by jessesquires** [comment]
https://github.com/apple/swift/pull/14502

**Comment by SD10** [comment]
Possible string index bug
https://twitter.com/lapcatsoftware/status/962347634408280065

**Comment by jessesquires** [comment]
Finally 
https://mobile.twitter.com/AirspeedSwift/status/962754808733036544

**Comment by RomanVolkov** [comment]
update for se-0195 https://github.com/apple/swift/pull/14546
switches from DynamicMemberLookupProtocol to @dynamicmemberlookup, 
"updates it for other changes in the compiler, improves diagnostics a bit, and adds new tests"

**Comment by RomanVolkov** [comment]
https://forums.swift.org/t/proposal-to-improve-the-standard-library-stride-types/9675

**Comment by BasThomas** [comment]
195 accepted blog post: https://forums.swift.org/t/se-0195-introduce-user-defined-dynamic-member-lookup-types/8658/160

**Comment by BasThomas** [comment]
https://forums.swift.org/t/pitch-add-compactmapvalues-to-dictionary/8741

**Comment by jessesquires** [comment]
Bool toggle

review kicking off soon: https://github.com/apple/swift-evolution/pull/782#issuecomment-364764667

implementation: https://github.com/apple/swift/pull/14586

**Comment by BasThomas** [comment]
https://twitter.com/dgregor79/status/963904855851991041

**Comment by RomanVolkov** [comment]
Pitch "Objective-C interoperability: Eliminate NSObjectProtocol" https://forums.swift.org/t/objective-c-interoperability-eliminate-nsobjectprotocol/9947

**Comment by jessesquires** [comment]
Bool toggle review
http://forums.swift.org/t/se-0199-adding-toggle-method-to-bool/9841

**Comment by jessesquires** [comment]
Adding #context

http://forums.swift.org/t/supplement-file-line-and-function-with-context/9505

**Comment by jessesquires** [comment]
Float.nextUp perf

http://forums.swift.org/t/is-floats-nextup-really-50-times-slower-than-necessary/9716

**Comment by BasThomas** [comment]
https://twitter.com/dgregor79/status/964248492729278464

Source compatibility is "fun": https://forums.swift.org/t/objective-c-interoperability-eliminate-nsobjectprotocol/9947/17?u=douglas_gregor

**Comment by BasThomas** [comment]
https://github.com/apple/swift-evolution/pull/787

**Comment by jessesquires** [comment]
https://useyourloaf.com/blog/replacing-flatmap-with-compactmap/

**Comment by BasThomas** [comment]
https://twitter.com/jckarter/status/965039238071726081

**Comment by BasThomas** [comment]
https://github.com/apple/swift-evolution/pull/789

**Comment by tapthaker** [comment]
https://davedelong.com/blog/2018/02/08/swift-protocols-wishlist/

Swift protocols wish list

**Comment by BasThomas** [comment]
https://www.dotconferences.com/2018/01/ben-cohen-extending-the-standard-library

**Comment by BasThomas** [comment]
https://twitter.com/tkremenek/status/966071276543492096

Swift to participate in Google Summer of Code, see: https://forums.swift.org/tags/gsoc-2018 if you are interested in participating!

**Comment by BasThomas** [comment]
https://github.com/apple/swift-evolution/pull/791

**Comment by BasThomas** [comment]
FYI, I am putting together the last bits today :)

**Comment by BasThomas** [comment]
Xcode 9.3 beta 3 + `xccov`: https://twitter.com/SmileyKeith/status/966089848904810496

**Comment by jessesquires** [comment]
@BasThomas 

Swift JIRA tickets now have "votes". Not sure when this was added.

I made a custom public filter to sort by highest voted bugs/issues.
https://bugs.swift.org/issues/?filter=11015

**Comment by BasThomas** [comment]
@jessesquires I think that's been there forever. 😁

**Comment by jessesquires** [comment]
@BasThomas lol oops 😳
