### ISSUE TITLE
[22][SR-1421] Starter task to improve `sourcekitd-test` output

### ISSUE THREAD

**Issue by modocache** [SwiftWeekly/swiftweekly.github.io#37]
[SR-1421](https://bugs.swift.org/browse/SR-1421): Document the `sourcekitd-test` tool, which is used to quickly experiment with SourceKit. This task will involve writing a small amount of C++. You'll learn about LLVM's command line interface library and its argument parser, as well as about Swift's SourceKit.

**Comment by jessesquires** [comment]
thanks @modocache ! 🙇 😄 🎉
