### ISSUE TITLE
Fix Danger errors

### ISSUE THREAD

**Issue by jessesquires** [SwiftWeekly/swiftweekly.github.io#381]
Looks like there was a problem here: https://github.com/SwiftWeekly/swiftweekly.github.io/pull/380#issuecomment-378986813

🤔 

Complaining about:

https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/Dangerfile#L36

Seems like a syntax error in `Dangerfile`

**Comment by BasThomas** [comment]
> undefined method `[]` for nil:NilClass.

Weird. Even if something is unexpectedly `nil`, I have no clue what the method `[]` does. Will investigate.

**Comment by jessesquires** [comment]
Looks like Danger is working fine at #383

Going to close.
