### ISSUE TITLE
Create a tool that gets the latest starter tasks

### ISSUE THREAD

**Issue by BasThomas** [SwiftWeekly/swiftweekly.github.io#389]
This feels like a "scripted" part of the newsletter; it would be nice to automate this.

I can imagine a script that you pass in the previous issue's "latest" start bug number and then gets all new ones since then (read: with a higher number).

https://docs.atlassian.com/software/jira/docs/api/REST/7.12.0/

**Comment by SD10** [comment]
Just throwing ideas out there but, you could use [peril's scheduler](https://github.com/danger/peril/blob/6e69f27b1b6d86f6fea0ad6d0cb9700f85e05033/source/db/index.ts#L74) to set up a daily task to analyze the apple/swift repo. 
You could check the current state of PRs such as:
- New PRs opened
- PRs merged
- PRs closed

You would need some sort of mongodb store to use the scheduler, mLab's 500mb free should suffice. It would also be useful to keep some daily state of the PR numbers in play.

I have zero time for open source at the moment, but always free to bounce ideas off of

**Comment by jeroenleenarts** [comment]
@fassko Is this issue still relevant? It seems to me Bas is describing a workflow he used and you nowadays are not?

**Comment by fassko** [comment]
We can close it now.

**Comment by BasThomas** [comment]
I never figured out how to automate this, unfortunately.
