### ISSUE TITLE
Create a tool that generates previews for urls and fills out repetition in proposal information

### ISSUE THREAD

**Issue by BasThomas** [SwiftWeekly/swiftweekly.github.io#390]
It would help to generate some sort of inline preview for urls (in the form of text?) to make writing an issue easier and faster.

Also, we could generate, based on a url, the `proposal xyz with number 123 is in review` lines that parses eg. the proposal title and corresponding swift forum post (or get the proposal url + title from the swift forum post url).

**Comment by jessesquires** [comment]
🎉 great idea

**Comment by jessesquires** [comment]
Actually -- I think the proposals themselves often contain most of the info you need.

You might be able to grab the proposals from GH and parse out the info needed

**Comment by SD10** [comment]
So probot has a plugin called [unfurl](https://github.com/probot/unfurl) which automatically unfurls links in GitHub issues. 

You could setup a [peril](https://github.com/danger/peril) instance to achieve something similar. 

Don't know if this helps. Here is a [preview of unfurling](https://github.com/probot/unfurl/issues/4#issue-269197750)

**Comment by SD10** [comment]
If you're looking to automate more stuff, you could also send out the tweet for the latest issue upon the merging the PR

**Comment by BasThomas** [comment]
> you could also send out the tweet for the latest issue upon merging the PR.

This is now automated with IFTTT where it regularly checks the rss feed and then posts in to Twitter. Would be nice though if we'd have some more control over the message we post; right now we have difficulties posting the tweet with the author's Twitter handle, for example.

**Comment by BasThomas** [comment]
This is done now :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
