### ISSUE TITLE
Reincarnate email sending functionality

### ISSUE THREAD

**Issue by fassko** [SwiftWeekly/swiftweekly.github.io#410]
During try! Swift we talked with @BasThomas and I explained that I think email format of newsletter is great as you can kind of mark to read for later.
I think we could talk here and there to look for company (or individual) who can sponsor newsletter email service.
What do you think?

What kind of service was used before?

**Comment by BasThomas** [comment]
I was thinking to indeed bring sponsorships back for this. @jessesquires, what do you think?

We used Mailchimp before I'm pretty sure.

**Comment by jessesquires** [comment]
👍 

Just noting that Bas and I are working on this

**Comment by BasThomas** [comment]
Done! 👍

**Comment by thii** [comment]
A self-hosted newsletter app is also an option. I think [Mailtrain](https://github.com/Mailtrain-org/mailtrain) on a free Heroku dyno would be enough. I can help on this.
