### ISSUE TITLE
[Translation] Chinese

### ISSUE THREAD

**Issue by wongzigii** [SwiftWeekly/swiftweekly.github.io#421]
Hi, all members from SwiftWeekly,

Just as [NSHipster.com](https://nshipster.com) to [NSHipster.cn](https://nshipster.cn/), [objc.io](https://www.objc.io/) to [objccn.io](https://objccn.io/), I would like to bring swiftweekly.github.io to Chinese' Swift developers, for tracking the news of the Swift community.

In the beginning, I've tried to create a PR to make this website to be multilingual. And I came accross  https://github.com/github/pages-gem/issues/401 , it seems like GitHub page does't have an official i18n Jekyll plugin to make it works so far :(.

~~So I created a new organization just likes objccn, called **swiftweeklycn**, and I am going to translate the latest issue every other Thursdays and deploy it to github-page.~~

FYI ~~*[The latest issue has already done and deployed](https://swiftweeklycn.github.io/issue-121/)*~~ .

Let me know what you think.

**Comment by jessesquires** [comment]
Thanks @wongzigii ! Seems like a really valuable resource for that community.

**Comment by jessesquires** [comment]
A few notes:

- Can you remove the "Subscribe" and "Sponsor" buttons and pages? (To avoid confusion with the proper newletter subscriptions and sponsors.)
- It looks like the footer links are broken (twitter, github, rss, etc.)

**Comment by jessesquires** [comment]
@BasThomas We should definitely share this in the next issue 😊

**Comment by wongzigii** [comment]
> Can you remove the "Subscribe" and "Sponsor" buttons and pages? (To avoid confusion with the proper newletter subscriptions and sponsors.)
> It looks like the footer links are broken (twitter, github, rss, etc.)

Will fix it ASAP, no worries.

**Comment by jessesquires** [comment]
Thanks @wongzigii !

**Comment by jessesquires** [comment]
Hey @wongzigii 

Where is the `swiftweeklycn` repo hosted? Would you like to move it under the `SwiftWeekly` GitHub organization? I think that would be great and a better way to keeps things organized. 😄 

cc @BasThomas Thoughts?

**Comment by BasThomas** [comment]
Hi @wongzigii!

This is awesome! I think it would indeed be a good idea to move that version to this organization as well.

@jessesquires: it is now hosted [here](https://github.com/swiftweeklycn/swiftweeklycn.github.io).

**Comment by jessesquires** [comment]
@BasThomas Ah I see.

Hm.... actually. It might be tricky to get everything to work with GH pages. Maybe not.

Looks like we could activate GH-pages for the `master` branch. 

Then the site would appear at: `https://swiftweekly.github.io/swiftweeklycn/`

**Comment by wongzigii** [comment]
Good idea. 

Maybe https://swiftweekly.github.io/cn/ would be shorter and better ? So I am going to transfer the repo to this organization and rename the repo name to `cn`. Additionly, I will drop that organization.

A few notes:

I use https://github.com/swiftweeklycn/_posts to seperate all posts as a gitsubmodule to keep it simple. Should I also transfer that repo too?

**Comment by wongzigii** [comment]
> You don’t have the permission to create repositories on SwiftWeekly

Seems like I don't have permission while doing transfer.

**Comment by jessesquires** [comment]
Hey @wongzigii ! I'll help with this now

**Comment by jessesquires** [comment]
@wongzigii Ok -- I just sent you an invite to the org. Once you accept, you should be able to transfer the repo. :) 

If you can't -- it's probably because we need to fix some permissions. Let me know 😄

**Comment by jessesquires** [comment]
> Maybe https://swiftweekly.github.io/cn/ would be shorter and clearer? So I am going to transfer the repo to this organization and rename the repo name to cn. Additionally, I will drop that organization.

Sounds great! 👍 

> 1. I currently using https://github.com/swiftweeklycn/_posts to separate all posts as a git-submodule to keep it simple. Should I also transfer that repo too?

Hm. I'm not sure. I don't think we'll need this once we move the main repo to the org. Here's what I'm thinking:

1. We transfer the `cn` repo under `swiftweekly`.
2. This repo is essentially just a copy of the main repo

Our publishing flow would be:

1. We publish a new issue on the main, english site
2. You can copy the new post `date-issue-##.md` to `cn/_posts`
3. Translate the post and push

It's a bit manual, I guess (copying the new post), but doesn't seem to bad. This way you can just translate the post in-line. What do you think?

OR -- maybe there's a way to do everything within the main `swiftweekly.github.io` repo and jekyll?

> 2. I've adjusted some font/font-size for better rendering in Chinese.

Sounds good to me. 👌

**Comment by wongzigii** [comment]
@jessesquires Done! BTW, I can't access the `cn` settings panel. 

> Can you remove the "Subscribe" and "Sponsor" buttons and pages? (To avoid confusion with the proper newletter subscriptions and sponsors.)

Should we bring back the sponsor and subscribe and point to the original link, cause the cn is now the subpage of main. (maybe not? I am not sure)

**Comment by jessesquires** [comment]
hey @wongzigii / @BasThomas 

I just setup some new teams / permissions for the org.

@wongzigii -- you should be an admin on `cn` now.

**Comment by jessesquires** [comment]
Now that we've got the main pieces in place. Let's close this out and continue the discussion at https://github.com/SwiftWeekly/cn/issues/1

😄
