### ISSUE TITLE
Subscribe is showing some odd fields

### ISSUE THREAD

**Issue by allenhumphreys** [SwiftWeekly/swiftweekly.github.io#453]
`MEMBER_RATING`, `LATITUDE`, `LONGITUDE`, etc. Is this right? I feel like when I signed up I didn't have this.

**Comment by jessesquires** [comment]
Thanks @allenhumphreys !

Can you clarify what you mean here? I just checked https://swiftweekly.github.io/subscribe/ and everything seems to be ok...

**Comment by allenhumphreys** [comment]
Following the link in the email to "View this email in your browser" take you to [here](https://us19.campaign-archive.com/?e=2c1562b04f&u=2951f6b6f2d9b152b48176dab&id=e26c97117f) and then clicking subscribe takes you [here](https://github.us19.list-manage.com/subscribe?u=2951f6b6f2d9b152b48176dab&id=a881f89716).

So it looks like more of a mail chimp thing, whether it can be "fixed"/changed or not may not be for here.

**Comment by jessesquires** [comment]
Ah, I see. Thanks @allenhumphreys !

I recommend subscribing via https://swiftweekly.github.io/subscribe/

But, we should definitely check the mailchimp setup/config. cc @BasThomas

**Comment by allenhumphreys** [comment]
Yeah, I mean, I'm already subscribed but I tried to get a subscribe page quickly via the email to share with friends and found a 🐉 :-)

Feel free to close as you see fit.

**Comment by BasThomas** [comment]
Huh, thanks for reporting this! Will take a look. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
I've reported this to Mailchimp — thanks for reaching out, @allenhumphreys! Let's see what they say.

**Comment by BasThomas** [comment]
I've updated it. It will now only ask for an email, first and last name. Thanks again!

**Comment by jessesquires** [comment]
🎉
