### ISSUE TITLE
Offer a dark theme of the website

### ISSUE THREAD

**Issue by BasThomas** [SwiftWeekly/swiftweekly.github.io#461]

**Comment by jessesquires** [comment]
this might be difficult with jekyll. not sure though.

i was planning on trying this with my personal site, so interested in learning how to do this!

**Comment by BasThomas** [comment]
I’ve seen some forks of jekyll themes that already include it; that could be an option to explore!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jpsim** [comment]
Isn't this "just" CSS though? Why would Jekyll care what your CSS does?

**Comment by jessesquires** [comment]
@jpsim yeah, i think you're correct.

**Comment by BasThomas** [comment]
True. Is all of this custom css?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jessesquires** [comment]
@BasThomas 

> Is all of this custom css?

What do you mean?

**Comment by jessesquires** [comment]
Oh. Yeah 😊 it's custom CSS:
https://github.com/SwiftWeekly/swiftweekly.github.io/tree/master/css

Well, "custom". It's Bootstrap with some minor overrides/customization.

Will probably need to switch to using SASS or something like that to make it easier.

**Comment by BasThomas** [comment]
I'm working on this 😊

**Comment by jessesquires** [comment]
@BasThomas nice! 🎉 looks good 🙌 

however, #469 might make this easier (specifically, upgrading bootstrap)

**Comment by BasThomas** [comment]
Ah, I'm probably going to just finish this and once Bootstrap has been upgraded we can revisit it :)
