### ISSUE TITLE
Upgrade bootstrap, use yarn for dependencies

### ISSUE THREAD

**Issue by jessesquires** [SwiftWeekly/swiftweekly.github.io#469]
- [x] Upgrade to [Bootstrap 4.x](https://getbootstrap.com) and jQuery 3.x
- [x] ~~- Upgrade to [Font Awesome 5](https://fontawesome.com/)~~ (Let's keep v4, installed via yarn)
- [ ] Use yarn to manage dependencies?

Note: the bootstrap upgrade is pretty significant and will require a decent amount of changes. The grid system is slightly different, some components have been removed, the basic "starter template" has been updated, and more.

Probably not super high priority, but definitely worth doing IMO.

---

I did all of this for jessesquires.com and it's been great.

**Comment by jeroenleenarts** [comment]
What would be the benefit to adopting yarn?
