### ISSUE TITLE
[146] Issue #146 - October 24, 2019

### ISSUE THREAD

**Issue by jpsim** [SwiftWeekly/swiftweekly.github.io#480]
To contribute to this issue, simply leave a comment here. Please also review [our contributing guidelines](https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/CONTRIBUTING.md).

The current draft for this issue in [`_drafts/`](https://github.com/SwiftWeekly/swiftweekly.github.io/tree/master/_drafts). If you want to contribute directly, feel free to [open a pull request](https://github.com/SwiftWeekly/swiftweekly.github.io/compare?expand=1).

**Comment by jpsim** [comment]
> Initial support for swift package manager in bazel

https://github.com/bazelbuild/rules_swift/pull/329

**Comment by fassko** [comment]
https://github.com/apple/swift-driver

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fassko** [comment]
> I just lost a stupid amount of time to https://github.com/apple/swift/pull/84. Any objections to me pulling it out, so CMakeCache.txt shows up in `git status` by default? Individuals who want to do in-source-tree builds can still add it to their local .git/info/exclude. (I haven't seen the original contributor of that PR around in a while either.)

https://forums.swift.org/t/un-gitignore-cmakecache-txt/29712

**Comment by fassko** [comment]
**Improving the representation of polymorphic interfaces in SIL with "substituted function types"**

> SIL has a lot of incidental complexity arising from representational issues in how we handle the types of polymorphically-callable functions such as protocol witnesses, class methods, and closures. Here is a proposed design for substituted function types, which tries to address some of these issues.
> ...


https://forums.swift.org/t/improving-the-representation-of-polymorphic-interfaces-in-sil-with-substituted-function-types/29711

**Comment by fassko** [comment]
Swift 5.1.1 is now available for [download](https://swift.org/download/).

It is a bug-fix release that addresses a [security issue](https://support.apple.com/en-us/HT210647) on Ubuntu platforms.

https://forums.swift.org/t/swift-5-1-1-released-linux-only/29732

**Comment by BasThomas** [comment]
267 scheduled https://github.com/apple/swift-evolution/blob/master/proposals/0267-where-on-contextually-generic.md

**Comment by BasThomas** [comment]
> New project announcement: Swift compiler driver reimplementation in Swift

@fassko I already included that one (last-minute!) in the previous issue 😄

**Comment by fassko** [comment]
**Heads up about potential update-checkout failures for fetches from the clang, llvm, compiler-rt, libcxx, clang-tools-extra, lldb repos**

> After some llvm-project monorepo preparation work @dexonsmith and I did yesterday, your update-checkout fetches for https://github.com/apple/swift-{clang,llvm,compiler-rt,libcxx,clang-tools-extra,lldb} might fail with errors ...

https://forums.swift.org/t/heads-up-about-potential-update-checkout-failures-for-fetches-from-the-clang-llvm-compiler-rt-libcxx-clang-tools-extra-lldb-repos/29746

**Comment by BasThomas** [comment]
https://twitter.com/Catfish_Man/status/1183899166331662337
https://twitter.com/Catfish_Man/status/1183900410613878784

**Comment by fassko** [comment]
Discussion about Source compatibility

https://forums.swift.org/t/source-compatibility/29814

**Comment by fassko** [comment]
**[Accepted] SE-0266: Synthesized Comparable conformance for enum types**

> The review for [SE-0266](https://github.com/apple/swift-evolution/blob/master/proposals/0266-synthesized-comparable-for-enumerations.md) has ended and the proposal has been [accepted](https://forums.swift.org/t/se-0266-synthesized-comparable-conformance-for-enum-types/29457/76).
>
> The proposal was received positively, and removes boilerplate code for many common cases.

https://forums.swift.org/t/accepted-se-0266-synthesized-comparable-conformance-for-enum-types/29854

**Comment by BasThomas** [comment]
264 returned for revision

**Comment by fassko** [comment]
> 264 returned for revision

https://forums.swift.org/t/returned-for-revision-se-0264-standard-library-preview-package/29865

**Comment by fassko** [comment]
https://twitter.com/johannesweiss/status/1184572894807900160

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BasThomas** [comment]
https://twitter.com/jckarter/status/1184904575435755520

> A Swift blog post by @pyaskevich about the architectural improvements we've been making to get better type error messages: https://swift.org/blog/new-diagnostic-arch-overview/

**Comment by fassko** [comment]
The GitHub swift-specific split llvm-project repositories are now read-only

> The transition to the llvm-project monorepo is happening today ([LLVM monorepo transition happening on Thursday, the 17th of October](https://forums.swift.org/t/llvm-monorepo-transition-happening-on-thursday-the-17th-of-october/29674)).

https://forums.swift.org/t/the-github-swift-specific-split-llvm-project-repositories-are-now-read-only/29911

**Comment by fassko** [comment]
Swift on the Server Work Group October 8th, 2019 meeting notes

https://forums.swift.org/t/october-8th-2019/29904

**Comment by fassko** [comment]
**Pitch: Add RangeSet and Related Collection Operations**

Here's a pitch to fill a missing chunk of functionality in the standard library around noncontiguous ranges of elements. Please take a look at the draft proposal below, and/or try out this new functionality by using the SwiftPM package here: https://github.com/natecook1000/swift-evolution/tree/rangeset_and_friends 

https://forums.swift.org/t/pitch-add-rangeset-and-related-collection-operations/29961

**Comment by fassko** [comment]
Starter task

[TF-935](https://bugs.swift.org/browse/TF-935) [Autodiff] [AD] Add `-enable-experimental-forward-mode-differentiation` flag

**Comment by fassko** [comment]
Trajectory for evaluating adding Automatic Differentiation to Swift

> One of the efforts of the Swift for TensorFlow project has been to explore adding features like Automatic Differentiation 10 to the Swift language. This is a powerful capability that can significantly enrich Swift’s potential as a programming language for scientific computing, numerics, and machine learning.
> 
> Speaking on behalf of the Swift Core Team, we are interested in evaluating incorporating this capability directly into the Swift language.

https://forums.swift.org/t/trajectory-for-evaluating-adding-automatic-differentiation-to-swift/30048

**Comment by fassko** [comment]
**SE-0267 — `where` clauses on contextually generic declarations**

> The review of [SE-0267 — where clauses on contextually generic declarations](https://github.com/apple/swift-evolution/blob/master/proposals/0267-where-on-contextually-generic.md) begins now and runs through October 31, 2019.

https://forums.swift.org/t/se-0267-where-clauses-on-contextually-generic-declarations/30051

**Comment by fassko** [comment]
**SE-0268: Refine didSet Semantics**

> The review of [SE-0268 — Refine didSet Semantics](https://github.com/apple/swift-evolution/blob/master/proposals/0268-didset-semantics.md) begins now and runs through October 31, 2019.

https://forums.swift.org/t/se-0268-refine-didset-semantics/30049

**Comment by BasThomas** [comment]
https://twitter.com/bsaeta/status/1186320375765819392

> The #S4TF team is collaborating with @tkremenek and the core #SwiftLang team to upstream language-integrated automatic differentiation, taking our work to the next phase. Once we're happy with the implementation, we'll go through Swift Evolution. https://forums.swift.org/t/trajectory-for-evaluating-adding-automatic-differentiation-to-swift/30048 Thx2all!

**Comment by BasThomas** [comment]
Finally https://twitter.com/Catfish_Man/status/1186424549455224832

**Comment by fassko** [comment]
[Accepted] SE-0263 ‘Add a String Initializer with Access to Uninitialized Storage’

The proposal [SE-0263](https://github.com/apple/swift-evolution/blob/master/proposals/0263-string-uninitialized-initializer.md) has been accepted.

https://forums.swift.org/t/accepted-se-0263-add-a-string-initializer-with-access-to-uninitialized-storage/30057

**Comment by fassko** [comment]
https://www.swiftbysundell.com/podcast/59

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fassko** [comment]
**Instance-level polymorphism**

I've seen some similar ideas discussed on the forums ([notably Polymorphic methods in enums](https://forums.swift.org/t/polymorphic-methods-in-enums/15093)) which are focused around the idea of improving the experience of attaching case-specific behavior to enums without having a totally fragmented implementation. I encountered this issue yet again yesterday and wanted to solicit feedback on some thoughts I had about potential solutions.

https://forums.swift.org/t/instance-level-polymorphism/30087

**Comment by fassko** [comment]
Autolinking enabled on GitHub for bugs.swift.org issues!

![https://aws1.discourse-cdn.com/swift/original/2X/7/76dab8d2c46975ca2f7cbbb05a717acd77dbbd01.gif](https://aws1.discourse-cdn.com/swift/original/2X/7/76dab8d2c46975ca2f7cbbb05a717acd77dbbd01.gif)


https://forums.swift.org/t/autolinking-enabled-on-github-for-bugs-swift-org-issues/30091

**Comment by BasThomas** [comment]
https://twitter.com/johannesweiss/status/1187045920409444353

> 🎉 Awesome! We've got the 1.0.0 tag of the async-http-client library: https://github.com/swift-server/async-http-client which means it will now follow SemVer and you can depend on it using `from: "1.0.0"` #SSWG
This is a true community effort, please keep the patches & issues coming!

**Comment by BasThomas** [comment]
https://twitter.com/johannesweiss/status/1187072832552890368

> It's release day today SwiftNIO 2.9.0 with quite a number of new features and over 20 PRs since 2.8.0: https://github.com/apple/swift-nio/releases/tag/2.9.0 🚀 https://twitter.com/johannesweiss/status/1187045920409444353
