### ISSUE TITLE
Audit for (and improve) accessibility

### ISSUE THREAD

**Issue by BasThomas** [SwiftWeekly/swiftweekly.github.io#484]
I just got sent this. (this uses the Chrome built-in tooling)

![image](https://user-images.githubusercontent.com/4190298/67642670-5efce080-f90e-11e9-95df-799afc9583fd.png)

We should investigate this and see where we can improve the accessibility

**Comment by jessesquires** [comment]
nice. how do you see this with chrome?

**Comment by jessesquires** [comment]
nevermind. found it. pretty cool.

**Comment by BasThomas** [comment]
Maybe you can share how to do that with Chrome? I don't know. Would love to give it a look and see what kind of improvements we can make :)

**Comment by jessesquires** [comment]
if you bring up the console, there's a new tab:

<img width="1439" alt="Screen Shot 2019-10-28 at 1 39 59 PM" src="https://user-images.githubusercontent.com/2301114/67716154-84c6cb80-f988-11e9-9431-d7ae6d09929f.png">

<img width="1439" alt="Screen Shot 2019-10-28 at 1 40 13 PM" src="https://user-images.githubusercontent.com/2301114/67716156-84c6cb80-f988-11e9-9256-c0fa5bceb41f.png">

**Comment by jessesquires** [comment]
my guess is that #469 might help 😄

**Comment by fbeeper** [comment]
#522 should address color contrast for syntax highlighting in light and dark mode, I'm also looking into the color contrast of other elements in the page, will keep you posted :)

**Comment by fbeeper** [comment]
#522 now includes all color changes not only syntax highlighting.

**Comment by fbeeper** [comment]
#523 solves some other very minor issues.

<img width="151" alt="image" src="https://user-images.githubusercontent.com/627312/82742763-e1b81380-9d16-11ea-8bf2-4f8b3a47098a.png">

**Comment by fbeeper** [comment]
Now, let me add this 100/100 is probably a bit too optimistic, I'm sure we can improve more things with more time. But, for now, it is a little step forward, no?

**Comment by jessesquires** [comment]
thanks so much @fbeeper !

**Comment by BasThomas** [comment]
woohoo!
