### ISSUE TITLE
Increase readability for code comments in dark mode

### ISSUE THREAD

**Issue by BasThomas** [SwiftWeekly/swiftweekly.github.io#485]
<img width="470" alt="image" src="https://user-images.githubusercontent.com/4190298/67658488-fcc9cd00-f959-11e9-8721-9e714c655bd3.png">
<img width="475" alt="image" src="https://user-images.githubusercontent.com/4190298/67658494-005d5400-f95a-11e9-8e2e-4d5ebf6d7d4f.png">

See https://swiftweekly.github.io/issue-146/

**Comment by BasThomas** [comment]
Maybe we can find a "dark mode" syntax highlighter for this? The green is also hard to read.

**Comment by fassko** [comment]
Maybe can incorporate with https://github.com/mannberg/splashtag I'm planning to integrate it to my blog and might be useful here but I haven't checked how does it work in dark mode.

**Comment by BasThomas** [comment]
Closing this for now as per f94b8d1ac7a687429939140a5b5d556534953245
