### ISSUE TITLE
associatetype

### ISSUE THREAD

**Issue by masters3d** [SwiftWeekly/swiftweekly.github.io#5]
I don't think is is s braking change in 2.2. I thought I read that it was just additive so that both types alias and associated type would compile in 2.2   I maybe be wrong. 

Loïc Lecrenier's proposal, "Replace typealias keyword with associatedtype for associated type declarations", has been accepted for Swift 2.2! **This is a breaking change, but it should be easy to migrate your existing code.**

**Comment by jessesquires** [comment]
Oops. :blush: 

You're right: https://github.com/apple/swift-evolution/blob/master/proposals/0011-replace-typealias-associated.md#proposed-approach

Thanks @masters3d ! :smile: 

What do submit a PR?

**Comment by jessesquires** [comment]
nevermind. got it! :smile:

**Comment by masters3d** [comment]
cool! thanks, I was driving. ;)

**Comment by jessesquires** [comment]
you can't submit pull requests while driving? :wink:
