### ISSUE TITLE
September issues

### ISSUE THREAD

**Issue by jessesquires** [SwiftWeekly/swiftweekly.github.io#50]
@modocache @jpsim 

Hello good sirs! Thanks so much for helping out in September 😊 

Here's the current tentative plan:

- [x] Issue 37, Sept 8: Jesse
- [x] Issue 38, Sept 15: JP
- [x] Issue 39, Sept 22: Brian
- [x] Issue 40, Sept 29: Brian

Of course, we can tweak this however we want. Or, if you know someone else who would like to contribute, that would work too. Let me know how this sounds! 😄

**Comment by jpsim** [comment]
I'm looking forward to pitching in 😄 . Any tips for collecting the information? You're a pro by now 😆

**Comment by jessesquires** [comment]
Haha. :smile: Yeah, let's sync up when it gets a bit closer

**Comment by BasThomas** [comment]
@jpsim / @modocache: let me know if I can help any of you with a specific thing / things!

**Comment by modocache** [comment]
Thanks! Pull requests for anything you find interesting would be great. I also don't usually follow Swift evolution, so some feedback on anything I write about that would be awesome as well.

**Comment by modocache** [comment]
Also:

1. Is there a specific time of day I should publish?
2. Do tweets/emails automatically get sent out when I publish? Or should I send those out manually somehow?

**Comment by jessesquires** [comment]
@modocache Should push to master before 12pm PST. (So 3pm EST)

Emails automatically go out by noon (based on new content in RSS feed). I've been doing the tweets manually. I should probably automate that eventually. 😄 

(I'll take care of the tweets manually for now. I have the best tweets. Everybody loves my tweets.)

**Comment by jessesquires** [comment]
I'll update `CONTRIBUTING.md` with that info.

**Comment by BasThomas** [comment]
@modocache I am on top Evolution! 👍

**Comment by BasThomas** [comment]
@jessesquires should we explicitly add the tweets are being sent manually at this time? That might prevent some questions in the future.

**Comment by jessesquires** [comment]
@BasThomas - done 👍

**Comment by BasThomas** [comment]
🙌

**Comment by jessesquires** [comment]
Hey all — I just updated [CONTRIBUTING](https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/CONTRIBUTING.md) again. Everything you need to know should be there. I pushed some infra updates this week too — adding `proselint`. So, it should be even easier to manage everything now. Let me know if you need anything else!

**Comment by BasThomas** [comment]
Thanks for all the work, @jessesquires!

**Comment by jessesquires** [comment]
@modocache you're up next! 🎉 😄 🙌

**Comment by modocache** [comment]
![giphy 4](https://cloud.githubusercontent.com/assets/552921/18561380/9c341456-7b4d-11e6-83ff-7ffa14562586.gif)

**Comment by modocache** [comment]
Pushed a draft for issue 39 here: https://github.com/SwiftWeekly/swiftweekly.github.io/commit/8c37d258d3956022cc80c98b146ab9f73b22a3b5

**Comment by modocache** [comment]
39 is ready for final review. Have a read here! #92

**Comment by modocache** [comment]
OK, published 39! Now I just have to wait for that email (automated) and tweet (via @jessesquires). 💯

**Comment by BasThomas** [comment]
Good job @modocache! 😀

**Comment by modocache** [comment]
Noticed one issue after publishing...

![screen shot 2016-09-22 at 1 22 15 pm](https://cloud.githubusercontent.com/assets/552921/18759262/bcdefa82-80c9-11e6-9c64-a36606837d73.png)

I'll look into it. It's OK to push changes to production, right? 😅

**Comment by BasThomas** [comment]
Should be no problem :)

**Comment by modocache** [comment]
Problem is: I don't really know why this is blank. It seems to be referencing a variable named `site.handle`. Maybe it's a Jekyll thing?

I'll take a look after this issue is published. :)

**Comment by BasThomas** [comment]
Seems this has broken previously? All old issues are having the same issue. 😕

**Comment by BasThomas** [comment]
I think Jesse broke this in 74de0a0. Try `.twitter.username` instead of `.handle`? Can't test locally at this moment myself, unfortunately.

**Comment by modocache** [comment]
Fixed in https://github.com/SwiftWeekly/swiftweekly.github.io/commit/cb1a00727fd7dab9e7ae1bf0b2147fa8bb27f592. Thanks, @BasThomas!! ❤️

**Comment by jessesquires** [comment]
lol whoops 😊 

thanks @BasThomas and @modocache !! 🙌 

![](https://media.giphy.com/media/l46Ct8dnc7vaiz7k4/giphy.gif)

**Comment by jessesquires** [comment]
Thanks all for the help! 

You have no idea how much I appreciate this! It helped so much and gave me some much needed time off-the-grid. 😊 

Would be more than happy to have each of you continue to contribute as much as you want! 👏
