### ISSUE TITLE
Issue templates

### ISSUE THREAD

**Issue by jessesquires** [SwiftWeekly/swiftweekly.github.io#504]
Hey @BasThomas @fassko 👋 

Just want to mention that I just created issue templates in the top-level [`.github` repo](https://github.com/SwiftWeekly/.github/tree/master/.github/ISSUE_TEMPLATE). They are now available. 

When you create a new issue, you'll see this now:

<img width="1040" alt="Screen Shot 2020-03-17 at 9 43 38 PM" src="https://user-images.githubusercontent.com/2301114/76926147-df5db700-6898-11ea-958b-e648548922d0.png">

Each template auto-fills info + labels. 😄 

(This will help especially with opening `current issue` issues. @BasThomas I know you wrote that script to automate opening these types of issues, but I think you can give the API a template name, so that should simplify your code.)

**Comment by jessesquires** [comment]
I couldn't think of a better place to mention this, so here we are 🤷‍♂ 😄

**Comment by BasThomas** [comment]
👌
