### ISSUE TITLE
Switch to GH Actions for CI

### ISSUE THREAD

**Issue by jessesquires** [SwiftWeekly/swiftweekly.github.io#513]
- [x] Remove `.travis.yml`
- [x] Add `.github/workflows/ci.yml`
- [x] Add danger API token to secrets, `DANGER_GITHUB_API_TOKEN`

This exact workflow should work:
https://github.com/jessesquires/jessesquires.com/blob/master/.github/workflows/ci.yml

**Comment by jessesquires** [comment]
@BasThomas @fassko it looks like travis-CI was broken on some recent PRs

This should be an easy/quick fix if we switch to GitHub Actions

**Comment by jessesquires** [comment]
I've added the `DANGER_GITHUB_API_TOKEN` to the repo secrets

**Comment by fassko** [comment]
I moved most of my projects t Github Actions. So far so good.

**Comment by BasThomas** [comment]
Sure, let's do this 👍
