### ISSUE TITLE
Contribution proposal

### ISSUE THREAD

**Issue by RickNln** [SwiftWeekly/swiftweekly.github.io#516]
Questions, Feedback: https://swiftweekly.github.io/authors/

Hi,

We recently announced his open-source project - dotenv-linter. It’s a lightning-fast tool to check your .env files for problems. dotenv-linter is written in Rust and can be used on any project regardless of the programming language.

I’m reaching out to kindly ask if you can add us to your newsletter.

Here the article where you can learn more about the project: https://evrone.com/dotenv-linter
dotenv-linter Github link: https://github.com/dotenv-linter/dotenv-linter

**Comment by jessesquires** [comment]
Thanks @RickNln ! Sounds like a cool project, but this is not really in the scope of what our newsletter is about.
