### ISSUE TITLE
Swift 5.3 Has NOT Been Released

### ISSUE THREAD

**Issue by jshier** [SwiftWeekly/swiftweekly.github.io#520]
Issue 160 has this statement:

> Swift 5.3 was released,

It has **NOT** been released. At best the branch has been cut but release builds are not available anywhere. It likely won't be released until Sept. / Oct.

**Comment by jshier** [comment]
Fixed by #519.

**Comment by BasThomas** [comment]
Oops; thanks for bringing it up 😅
