### ISSUE TITLE
Feedback for Issue #162

### ISSUE THREAD

**Issue by Mordil** [SwiftWeekly/swiftweekly.github.io#529]
**Link to newsletter issue:** https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/_posts/2020-06-18-issue-162.md

## Feedback:

Swift on Server Working Group (SSWG) proposals should be listed as `SSWG-<proposal number>` rather than the `SE-<proposal number>` as it was in issue 162.

SSWG pitches and proposals are distinctly different and separate from Swift Evolution and the numberings will clash and have the potential for confusing readers.

**Comment by jessesquires** [comment]
Thanks @Mordil ! We'll get this fixed.

**Comment by BasThomas** [comment]
Woops, thanks — fixed.
