### ISSUE TITLE
[166] Issue #166- August 13, 2020

### ISSUE THREAD

**Issue by BasThomas** [SwiftWeekly/swiftweekly.github.io#536]
To contribute to this issue, simply leave a comment here. Please also review [our contributing guidelines](https://github.com/SwiftWeekly/.github/blob/master/CONTRIBUTING.md).

The current draft for this issue, if any, will be in [`_drafts/`](https://github.com/SwiftWeekly/swiftweekly.github.io/tree/main/_drafts). 

If you want to contribute directly, feel free to [open a pull request](https://github.com/SwiftWeekly/swiftweekly.github.io/compare?expand=1).

**Comment by BasThomas** [comment]
Are you taking this one @fassko?

**Comment by fassko** [comment]
Yep. As we agreed every second on me. 👌

**Comment by fassko** [comment]
Organizing stored properties in extensions

https://forums.swift.org/t/organizing-stored-properties-in-extensions/38902

**Comment by fassko** [comment]
Deferred property wrappers


https://forums.swift.org/t/deferred-property-wrappers/38931

**Comment by fassko** [comment]
Create your first HTTP endpoint with Swift on AWS Lambda

https://fabianfett.de/swift-on-aws-lambda-creating-your-first-http-endpoint

**Comment by fassko** [comment]
https://twitter.com/mattt/status/1289327001115869185

https://twitter.com/mattt/status/1289327755662745601

**Comment by fassko** [comment]
Sort(by:) min(by:) max(by:) with keyPaths

https://forums.swift.org/t/sort-by-min-by-max-by-with-keypaths/38976

**Comment by fassko** [comment]
Is it permitted to remove `@inlinable` from a function?

https://forums.swift.org/t/is-it-permitted-to-remove-inlinable-from-a-function/38938

> Ben_Cohen
>
> Yes and no. It depends on the function.

**Comment by fassko** [comment]
CMS on top of Vapor https://theswiftdev.com/getting-started-with-feather-cms/

**Comment by fassko** [comment]
Maybe fun one https://twitter.com/dgregor79/status/1290517038473961473

**Comment by BasThomas** [comment]
https://spec.fm/podcasts/swift-unwrapped/aC5JVWoo

**Comment by fassko** [comment]
https://twitter.com/olebegemann/status/1290673766046011393

**Comment by fassko** [comment]
Swift on the Server Workgroup July 29th, 2020 meeting notes

https://forums.swift.org/t/july-29th-2020/39107

**Comment by fassko** [comment]
Ironing out `ManagedBuffer` API wrinkles

https://forums.swift.org/t/ironing-out-managedbuffer-api-wrinkles/39072

**Comment by fassko** [comment]
Package Manager: Executable-Only Dependencies

https://forums.swift.org/t/package-manager-executable-only-dependencies/39070

**Comment by fassko** [comment]
fun one https://twitter.com/jeanqasaur/status/1290883041418649600

**Comment by fassko** [comment]
The state of Swift documentation

https://forums.swift.org/t/the-state-of-swift-documentation/39130

**Comment by fassko** [comment]
https://harshil.net/blog/swift-sequence-collection-array

**Comment by fassko** [comment]
SSWG-0015: Swift Service Lifecycle

https://forums.swift.org/t/sswg-0015-swift-service-lifecycle/39157

**Comment by fassko** [comment]
Generic Connection Pool

https://forums.swift.org/t/generic-connection-pool/39161

**Comment by fassko** [comment]
https://twitter.com/johannesweiss/status/1291678625763336192

**Comment by fassko** [comment]
https://twitter.com/tiborbodecs/status/1291703405476446208

**Comment by BasThomas** [comment]
https://twitter.com/johannesweiss/status/1292360924309979136

**Comment by fassko** [comment]
Kitura Is Now a Community Project

https://forums.swift.org/t/kitura-is-now-a-community-project/39199

**Comment by fassko** [comment]
https://thenewstack.io/swifts-chris-lattner-on-the-possibility-of-machine-learning-enabled-compilers/

**Comment by fassko** [comment]
https://forums.swift.org/t/adding-a-benchmark/39276

**Comment by fassko** [comment]
https://github.com/SwiftXcode/swift-lambda

**Comment by fassko** [comment]
https://swiftbysundell.com/articles/deep-dive-into-swift-function-builders/

**Comment by fassko** [comment]
https://twitter.com/mishaldshah/status/1293278153050173440

**Comment by fassko** [comment]
fun https://twitter.com/aalonso128/status/1293418352023613440

**Comment by fassko** [comment]
What? :P https://twitter.com/slava_pestov/status/1293294811034918914
