### ISSUE TITLE
Set up GitHub sponsorship

### ISSUE THREAD

**Issue by fassko** [SwiftWeekly/swiftweekly.github.io#574]
Idea from @zntfdr to set up sponsorship here in GitHub.
Need to explore this.

**Comment by jeroenleenarts** [comment]
@fassko Here are the steps: https://docs.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/setting-up-github-sponsors-for-your-organization

Only an owner of the organization can do this. And I think there can be only one payout account configured. It should take only a few minutes to enter all the info.

Biggest topics to think about are "what is your sponsorship goal" and sponsorship tiers.
