### ISSUE TITLE
Can't subscribe via FireFox

### ISSUE THREAD

**Issue by jonniedarko** [SwiftWeekly/swiftweekly.github.io#594]
## Describe the problem

Could not sign up for newsletter via https://swiftweekly.github.io/subscribe/
Was able to via chrome but only did so because happened to have chrome open for testing

## General information

 - OS version: MacOs 10.15
 - Browser version: Firefox 85.0.1 (64-bit)
 - Device: Mac

**Comment by fassko** [comment]
Hi @jonniedarko, maybe do you know what the issue is? Thanks, I will look into it.

**Comment by jonniedarko** [comment]
it seemed like a rejected request but other then that I don't have any more details, sorry should have screen shot the error

**Comment by jeroenleenarts** [comment]
Probably this is fixed with the new setup. Closing this issue because the underlying sign-up flow has changed significantly.
