### ISSUE TITLE
Subscribe via email?

### ISSUE THREAD

**Issue by jessesquires** [SwiftWeekly/swiftweekly.github.io#6]
https://twitter.com/orta/status/687668665198731264

**Comment by garricn** [comment]
Yes please 😄

**Comment by kylejm** [comment]
:+1:

**Comment by kylejm** [comment]
Perhaps a [Mandril](https://www.mandrill.com), [Mailgun](https://www.mailgun.com) or similar step could be run by Travis CI (#9) after successful deploy?

**Comment by kylejm** [comment]
An interim solution I'm using is to turn on notifications for [@swiftlybrief](http://twitter.com/swiftlybrief).

**Comment by jessesquires** [comment]
![img](https://media.giphy.com/media/5mBE2MiMVFITS/giphy.gif)
