### ISSUE TITLE
Transfer sending of newsletters out of Mailchimp

### ISSUE THREAD

**Issue by jeroenleenarts** [SwiftWeekly/swiftweekly.github.io#605]
In agreement with Kirstaps I am working on hosting the newsletter in a cheaper way that does not detract from the quality of the entire experience.

- [x] setup new mail service on sendy instance
- [x]  configure Amazon SES DKIM whitelisting this involves DNS settings on new domain.
- [x]  testing
- [x]  merge 602 (as said can be done “now”)
- [x]  configure landing pages on my newsletter config
- [x]  Merge 603 before issue 180
- [x]  Test if signups work as intended.
- [x] Pause rss auto send campaign on Mailchimp
- [x]  export/import existing subscribers
- [ ] Keep an eye on subs/unsubs on Mailchimp and transfer those as well
- [x] Add newsletter template rendering to jekyll scripting. #607 #608
- [x] Source newsletter from rendered template.
- [x] UTM rendering according to format: `utm_source=Swift_Weekly_Brief&utm_medium=email&utm_campaign=Issue_179` so we never forget to add it.
- [x]  cancel Mailchimp before the 24th.

Related:
#602 #603

**Comment by jeroenleenarts** [comment]
Some improvements done today, Added to checklist.

**Comment by fassko** [comment]
@jeroenleenarts I canceled Mailchimp and it seems that everything is working so we can close this?
