### ISSUE TITLE
Point the new swiftweeklybrief.com domain to github pages.

### ISSUE THREAD

**Issue by jeroenleenarts** [SwiftWeekly/swiftweekly.github.io#610]
Recently @fassko registered swiftweeklybrief.com

We should publish the current https://swiftweekly.github.io/ under the new domain.

I think is Github's howto guide: https://docs.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site

- [ ] Configure the repo accept the new domain name.
- [ ] Make sure DNS is configured correctly to point to this github pages instance.
- [ ] Adopt the new "friendly" email address associated with this new domain name.
- [ ] Update any references to the new domain.
- [ ] …

**Comment by jeroenleenarts** [comment]
Implemented.

**Comment by fassko** [comment]
Thank you @jeroenleenarts !
