### ISSUE TITLE
CSS looks bad / difficult to read

### ISSUE THREAD

**Issue by jessesquires** [SwiftWeekly/swiftweekly.github.io#623]
I'm not sure what happened, but the CSS on the site looks way off. 

There's double or triple spacing everywhere, which makes it very difficult to read.

The best thing to do is probably remove most of the custom CSS and just use the Bootstrap defaults.

**Comment by jeroenleenarts** [comment]
Not sure if bug is the right tag. But it does look a bit complex.

I am in no way versed in HTML / CSS. So help is appreciated.

@fassko I'm ok with having a stab at this. I expect to have some sort of resolution on this in like a week or so. It depends a bit on my schedule.

**Comment by jeroenleenarts** [comment]
Atleast the triple spaces are now gone in the CSS.

**Comment by jeroenleenarts** [comment]
Had a look at things. The reason the CSS is the way it is, I think, is to support dark/light mode.

**Comment by yas-sisodia** [comment]
@jessesquires can you please assign this task to me  I can solve this problem
