### ISSUE TITLE
[183] Issue #183 - April 22, 2021

### ISSUE THREAD

**Issue by fassko** [SwiftWeekly/swiftweekly.github.io#631]
To contribute to this issue, simply leave a comment here. Please also review [our contributing guidelines](https://github.com/SwiftWeekly/swiftweekly.github.io/blob/main/CONTRIBUTING.md).

The current draft for this issue in [`_drafts/`](https://github.com/SwiftWeekly/swiftweekly.github.io/tree/main/_drafts). If you want to contribute directly, feel free to [open a pull request](https://github.com/SwiftWeekly/swiftweekly.github.io/compare?expand=1).

**Comment by fassko** [comment]
SE-0306 (Second Review): Actors

https://forums.swift.org/t/se-0306-second-review-actors/47291

**Comment by fassko** [comment]
Pitch: non-static & non-generic attributes for protocols

https://forums.swift.org/t/pitch-non-static-non-generic-attributes-for-protocols/47280

**Comment by fassko** [comment]
[Pitch] Add `indexed()` and `Collection` conformances for `enumerated()` and `zip(_:_:)`

https://forums.swift.org/t/pitch-add-indexed-and-collection-conformances-for-enumerated-and-zip/47288

**Comment by mackoj** [comment]
Syntax highlighting in lap is coming...

https://github.com/apple/sourcekit-lsp/pull/279

**Comment by fassko** [comment]
Make it Official: the “Undocumented/Private API” signifier

https://forums.swift.org/t/make-it-official-the-undocumented-private-api-signifier/47381

**Comment by fassko** [comment]
https://youtu.be/pSTU6UlA4uw

**Comment by fassko** [comment]
SE-0310: Effectful Read-only Properties

https://forums.swift.org/t/se-0310-effectful-read-only-properties/47401

**Comment by fassko** [comment]
[Returned for revision] SE-0305: Package Manager Binary Target Improvements

https://forums.swift.org/t/returned-for-revision-se-0305-package-manager-binary-target-improvements/47441

**Comment by fassko** [comment]
SE-0303 (2nd review): Package Manager Extensible Build Tools

https://forums.swift.org/t/se-0303-2nd-review-package-manager-extensible-build-tools/47438

**Comment by fassko** [comment]
Why is `Dictionary[position:]` not settable?

https://forums.swift.org/t/why-is-dictionary-position-not-settable/47435

**Comment by fassko** [comment]
Swift on the Server Workgroup meetings

https://forums.swift.org/t/march-17th-2021/47427
https://forums.swift.org/t/march-31st-2021/47404

**Comment by fassko** [comment]
https://github.com/apple/swift/pull/36940

**Comment by mackoj** [comment]
https://github.com/apple/sourcekit-lsp/pull/388

**Comment by mackoj** [comment]
Async/Await in swift NIO ?

https://github.com/apple/swift-nio/pull/1701

**Comment by fassko** [comment]
SE-0311: Task-local values

https://forums.swift.org/t/se-0311-task-local-values/47478

**Comment by theblixguy** [comment]
SE-0309: Unlock existential for all protocols

https://forums.swift.org/t/se-0309-unlock-existential-types-for-all-protocols/47515

**Comment by fassko** [comment]
https://twitter.com/towernter/status/1383815365520629760

**Comment by fassko** [comment]
SE-0309: Unlock existential types for all protocols

https://forums.swift.org/t/se-0309-unlock-existential-types-for-all-protocols/47515

**Comment by jpsim** [comment]
https://github.com/swift-server/swift-backtrace/pull/42: Backtrace: enable support for Windows

**Comment by fassko** [comment]
https://holyswift.app/single-forward-pipe-operator-in-swift

**Comment by fassko** [comment]
https://developer.apple.com/documentation/xcode-release-notes/xcode-12_5-release-notes#Swift

**Comment by fassko** [comment]
https://forums.swift.org/t/swift-5-5-nightly-development-snapshots/47594
