### ISSUE TITLE
Automate tweets for new issues

### ISSUE THREAD

**Issue by BasThomas** [SwiftWeekly/swiftweekly.github.io#68]

**Comment by jessesquires** [comment]
I've never used the twitter API, so I don't have much experience with this.

If we could integrate with travis-ci, that would be awesome.

**Comment by jessesquires** [comment]
Maybe we can use https://ifttt.com for this?

**Comment by BasThomas** [comment]
Yeah, probably! And you would want to connect it to receiving the already automated mail?

**Comment by jessesquires** [comment]
Hm... not sure how that would work. I was hoping we could have IFTTT listen for changes in the RSS feed, then tweet based on that. (Which is actually how to the emails work, too.)

**Comment by BasThomas** [comment]
Didn't think of that, but that's an even better idea!

**Comment by BasThomas** [comment]
Something like this should do the trick: 
<img width="486" alt="screen shot 2016-11-30 at 21 02 45" src="https://cloud.githubusercontent.com/assets/4190298/20769005/73db351e-b740-11e6-9c71-f7b9fcfdd0bd.png">

**Comment by BasThomas** [comment]
Can I help with this?

**Comment by jessesquires** [comment]
@BasThomas sure! I've been slacking here 😄

**Comment by BasThomas** [comment]
Let me see if I can this running on a dummy account and see how it does. :)

**Comment by BasThomas** [comment]
I've been testing this over the past few weeks and it seems like it's working with IFTTT. In your IFTTT Settings though, make sure to disable link shortening to prevent the usage of `ift.tt` urls instead of `swiftweekly.github.io`

**Comment by BasThomas** [comment]
![img_0285](https://cloud.githubusercontent.com/assets/4190298/25704793/31cba86a-30db-11e7-9ea7-7d7412c373d6.PNG)
This is the recipe I am using. Obviously, we would not want to send a DM, put to post a tweet. ☺️

This posts eg. `Issue #68 swiftweekly.github.io/issue-68 written by Bas Broek`... only thing is it uses the author name, not the Twitter name. I think this can be changed?

**Comment by jessesquires** [comment]
This is great! 💯  

@BasThomas -- thanks so much for looking into this. I'll get this setup over the weekend. 

Still need to create an IFTTT account 😅  lol

I'm not sure about author name vs twitter handle.

IFTTT uses the rss/atom tags right?

**Comment by BasThomas** [comment]
Yes, the `{{EntryTitle}}` stuff just hooks into the RSS feed.

**Comment by jessesquires** [comment]
lol forgot to do this 😢 will definitely do it this week!

**Comment by jessesquires** [comment]
ok! just set this up. not sure if it's working. i guess we'll see next week 😅

**Comment by BasThomas** [comment]
Woo, nice! If you're not sure - I tested it for two weeks just sending myself a Twitter DM instead of tweeting. :)

**Comment by jessesquires** [comment]
it works!

https://twitter.com/swiftlybrief/status/865638949384994818

**Comment by BasThomas** [comment]
Yay!

**Comment by BasThomas** [comment]
The only thing we should still try to figure out is if we can use the author's Twitter handle instead of the author's full name. 🤔
