### ISSUE TITLE
[38] Issue #38, Sept. 15, JP

### ISSUE THREAD

**Issue by jessesquires** [SwiftWeekly/swiftweekly.github.io#74]
Let's use this issue for any discussion regarding Issue 38. 

I'll probably be commenting here with links every once in awhile to help out. 😄 

> /cc: @modocache @BasThomas

**Comment by jessesquires** [comment]
The empty draft is all ready to go 😄 

https://github.com/SwiftWeekly/swiftweekly.github.io/blob/master/_drafts/2016-09-15-issue-38.md

**Comment by jpsim** [comment]
issue is out, thanks all! http://swiftweekly.github.io/issue-38/
