### ISSUE TITLE
[38] Why aren't Double/Int bridged to NSNumber on Linux?

### ISSUE THREAD

**Issue by modocache** [SwiftWeekly/swiftweekly.github.io#75]
tl;dr: Because bridging via the ClangImporter is currently coupled with the presence of an Objective-C runtime.

- Original question: https://lists.swift.org/pipermail/swift-corelibs-dev/Week-of-Mon-20160905/000921.html
- Answer: https://lists.swift.org/pipermail/swift-corelibs-dev/Week-of-Mon-20160905/000924.html

Really interesting discussion; we should digest it and include it in issue 38 (#74)!

**Comment by modocache** [comment]
I think this is the same reason that Android ports, both of the Swift stdlib and of swift-corelibs-foundation, involved adding additional casts: https://github.com/apple/swift-corelibs-foundation/pull/622/files#diff-f731010b894263672b9190abbdd789ddR450

**Comment by jpsim** [comment]
Thanks for linking to that discussion... although I'm not convinced the ClangImporter is involved here.

I still think it's worth adding to the article to highlight that despite _portability_ having been a strong goal for Swift 3 [[0]](https://github.com/apple/swift-evolution#development-major-version--swift-30), there are still important areas where the behavior varies between platforms, especially bridging.

**Comment by jpsim** [comment]
issue is out, thanks @modocache! http://swiftweekly.github.io/issue-38/
