### ISSUE TITLE
[38] First appearances of Swift 3.1 ?

### ISSUE THREAD

**Issue by jessesquires** [SwiftWeekly/swiftweekly.github.io#79]
https://github.com/apple/swift/pull/4690/files

😮

**Comment by BasThomas** [comment]
😳

**Comment by BasThomas** [comment]
On `swift-evolution`: https://github.com/apple/swift-evolution/pull/522/files

**Comment by jpsim** [comment]
issue is out, thanks all! http://swiftweekly.github.io/issue-38/
