### ISSUE TITLE
How do you refer to yourself?

### ISSUE THREAD

**Issue by modocache** [SwiftWeekly/swiftweekly.github.io#94]
The weekly usually refers to people in the third person:

> JP Simard rewrote the entire compiler to be much faster.

What happens if the author and the subject of the sentence are the same person? For example, in issue 39, I wrote:

> Brian Gesiak sent a pull request to mark internal variables as final, which works around the bug in some cases.

Should I instead write this?

> I sent a pull request to mark internal variables as final, which works around the bug in some cases.

On the one hand, it's weird to refer to myself in the third-person. On the other, "I" isn't in line with the rest of the document.

Thoughts? 🙌

**Comment by BasThomas** [comment]
Although I can image it sounds weird, I think it's the easiest to refer to yourself in 3rd person. Because there are different people writing the Weekly Brief now, using "I" can become confusing.

**Comment by jessesquires** [comment]
Yeah -- I've done both in the past I think (can't remember).

But, I think I agree that 3rd-person is probably the least confusing.

**Comment by modocache** [comment]
Agree, third person it is. Thanks!
